var compounds = [
    {
        id: '45bfc664-9b49-49d3-a7bf-314be5466f41',
        class: 'excipient',
        name: 'benzyl benzoate',
        translations: {
            en: 'benzyl benzoate',
            fr: 'benzoate de benzyle',
            es: 'benzoato de bencilo',
            de: 'Benzylbenzoat',
            it: 'benzoato di benzile',
            nl: 'benzylbenzoaat',
            pt: 'benzoato de benzilo',
            ru: 'бензилбензоат',
            ja: '安息香酸ベンジル',
            zh: '苯甲酸苄酯',
            ko: '벤질 벤조에이트',
            ar: 'بنزيل بنزوات',
            hi: 'बेंजिल बेंजोएट',
            id: 'benzil benzoat',
            tr: 'benzil benzoat',
            pl: 'benzoesan benzylu',
            sv: 'bensylbensoat',
            da: 'benzylbenzoat',
            no: 'benzylbenzoat',
            cs: 'benzyl-benzoát',
            hu: 'benzil-benzoát',
            vi: 'benzyl benzoate'
        },
        pubchemid: null,
        self_id: 'benzyl_benzoate',
        molecular_weight: 212.24,
        density: 1.118,
        viscosityArray: [ 8.292 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 2,
        mg_per_ml: 0,
        purity: 100,
        basis: 'v_v_percent',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.198
    },
    {
        id: 'd77898ce-7068-4633-9d7a-539a15265dc2',
        class: 'excipient',
        name: 'benzyl alcohol',
        translations: {
            en: 'benzyl alcohol',
            fr: 'alcool benzylique',
            es: 'alcohol bencílico',
            de: 'Benzylalkohol',
            it: 'alcol benzilico',
            nl: 'benzylalcohol',
            pt: 'álcool benzílico',
            ru: 'бензиловый спирт',
            ja: 'ベンジルアルコール',
            zh: '苯甲醇',
            ko: '벤질 알코올',
            ar: 'كحول بنزيل',
            hi: 'बेंजिल अल्कोहल',
            id: 'alkohol benzil',
            tr: 'benzil alkol',
            pl: 'alkohol benzylowy',
            sv: 'bensylalkohol',
            da: 'benzylalkohol',
            no: 'benzylalkohol',
            cs: 'benzylalkohol',
            hu: 'benzil-alkohol',
            vi: 'benzyl alcohol'
        },
        pubchemid: null,
        self_id: 'benzyl_alcohol',
        molecular_weight: 108.1378,
        density: 1.044,
        viscosityArray: [ 5.474 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 20,
        mg_per_ml: 0,
        purity: 100,
        basis: 'v_v_percent',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.11,
        cas_no: '100-51-6',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 1.1789,
        formula: 'C7H8O',
        smiles: 'OCc1ccccc1'
    },
    {
        id: 'a7e55bf6-ec58-46f8-8164-22d4eb0cfa5d',
        class: 'excipient',
        name: 'ethanol',
        translations: {
            en: 'ethanol',
            fr: 'éthanol',
            es: 'etanol',
            de: 'Ethanol',
            it: 'etanolo',
            nl: 'ethanol',
            pt: 'etanol',
            ru: 'этанол',
            ja: 'エタノール',
            zh: '乙醇',
            ko: '에탄올',
            ar: 'إيثانول',
            hi: 'एथेनॉल',
            id: 'etanol',
            tr: 'etanol',
            pl: 'etanol',
            sv: 'etanol',
            da: 'ethanol',
            no: 'etanol',
            cs: 'ethanol',
            hu: 'etanol',
            vi: 'ethanol'
        },
        pubchemid: 702,
        self_id: 'ethanol',
        molecular_weight: 46.07,
        density: 0.785,
        viscosityArray: [ 1.04 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 20,
        mg_per_ml: 0,
        purity: 100,
        basis: 'v_v_percent',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.265,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '0b90c6fb-9dcd-4b9e-bb41-4543872157ff',
        class: 'excipient',
        name: 'chlorobutanol',
        log_p: 0.9976999999999998,
        translations: {
            en: 'chlorobutanol',
            fr: 'chlorobutanol',
            es: 'clorobutanol',
            de: 'Chlorobutanol',
            it: 'clorobutanolo',
            nl: 'chlorobutanol',
            pt: 'clorobutanol',
            ru: 'хлоробутанол',
            ja: 'クロロブタノール',
            zh: '氯丁醇',
            ko: '클로로부탄올',
            ar: 'كلوروبوتانول',
            hi: 'क्लोरोब्यूटानॉल',
            id: 'klorobutanol',
            tr: 'klorobutanol',
            pl: 'chlorobutanol',
            sv: 'klorobutanol',
            da: 'chlorobutanol',
            no: 'klorobutanol',
            cs: 'chlorobutanol',
            hu: 'klórbutanol',
            vi: 'chlorobutanol'
        },
        pubchemid: null,
        self_id: 'chlorobutanol',
        molecular_weight: 108.567,
        density: 1.317,
        viscosityArray: [ 10 ],
        viscosityTempArray: [ 100 ],
        melting_point: [ 78, 95 ],
        mls: 0,
        grams: 0,
        v_v_percent: 20,
        mg_per_ml: 0,
        purity: 100,
        basis: 'v_v_percent',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.11,
        cas_no: '928-51-8',
        image: null,
        mol2d: null,
        mol3d: null,
        formula: 'C4H9ClO',
        smiles: 'OCCCCCl'
    },
    {
        id: 'faca1ddd-98d7-4474-8533-eefbcff3a633',
        class: 'excipient',
        name: 'Sterile Water for Injection',
        translations: {
            en: 'Sterile Water for Injection',
            fr: 'Eau stérile pour injection',
            es: 'Agua estéril para inyección',
            de: 'Steriles Wasser zur Injektion',
            it: 'Acqua sterile per iniezione',
            nl: 'Steriel water voor injectie',
            pt: 'Água estéril para injeção',
            ru: 'Стерильная вода для инъекций',
            ja: '注射用水',
            zh: '注射用水',
            ko: '주사용 멸균수',
            ar: 'ماء معقم للحقن',
            hi: 'इंजेक्शन के लिए बाँझ पानी',
            id: 'Air Steril untuk Injeksi',
            tr: 'Enjeksiyonluk Steril Su',
            pl: 'Woda do wstrzykiwań jałowa',
            sv: 'Sterilt vatten för injektion',
            da: 'Sterilt vand til injektion',
            no: 'Sterilt vann til injeksjon',
            cs: 'Sterilní voda pro injekci',
            hu: 'Steril injekcióhoz való víz',
            vi: 'Nước vô trùng để tiêm'
        },
        pubchemid: 962,
        self_id: 'sterile-water-for-injection',
        molecular_weight: 18.02,
        density: 1,
        viscosityArray: [ 0.89 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.1,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '1071ad59-dbc7-45ae-aa56-55dd32f4fd11',
        class: 'excipient',
        name: 'ethyl oleate',
        translations: {
            en: 'ethyl oleate',
            fr: "oléate d'éthyle",
            es: 'oleato de etilo',
            de: 'Ethyloleat',
            it: 'oleato di etile',
            nl: 'ethyloleaat',
            pt: 'oleato de etila',
            ru: 'этилолеат',
            ja: 'オレイン酸エチル',
            zh: '油酸乙酯',
            ko: '에틸 올리에이트',
            ar: 'أولييت الإيثيل',
            hi: 'एथिल ओलिएट',
            id: 'etil oleat',
            tr: 'etil oleat',
            pl: 'oleinian etylu',
            sv: 'etyloleat',
            da: 'ethyloleat',
            no: 'etyloleat',
            cs: 'ethyloleát',
            hu: 'etil-oleát',
            vi: 'ethyl oleate'
        },
        pubchemid: 5363269,
        self_id: 'ethyl_oleate',
        molecular_weight: 310.5145,
        density: 0.87,
        viscosityArray: [ 5.15 ],
        viscosityTempArray: [ 25 ],
        evaporation_point: 250.15,
        melting_point: 217,
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        cas_no: '111-62-6',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 6.587,
        formula: 'C20H38O2',
        smiles: 'CCCCCCCCC=CCCCCCCCC(=O)OCC'
    },
    {
        id: '7936e672-b600-4368-8f88-1fc9c3d16e32',
        class: 'excipient',
        name: 'castor oil',
        translations: {
            en: 'castor oil',
            fr: 'huile de ricin',
            es: 'aceite de ricino',
            de: 'Rizinusöl',
            it: 'olio di ricino',
            nl: 'ricinusolie',
            pt: 'óleo de rícino',
            ru: 'касторовое масло',
            ja: 'ヒマシ油',
            zh: '蓖麻油',
            ko: '피마자유',
            ar: 'زيت الخروع',
            hi: 'अरंडी का तेल',
            id: 'minyak jarak',
            tr: 'hint yağı',
            pl: 'olej rycynowy',
            sv: 'ricinolja',
            da: 'ricinusolie',
            no: 'ricinusolje',
            cs: 'ricinový olej',
            hu: 'ricinusolaj',
            vi: 'dầu thầu dầu'
        },
        pubchemid: null,
        self_id: 'castor',
        molecular_weight: null,
        density: 0.96,
        viscosityArray: [ 580, 283, 36 ],
        viscosityTempArray: [ 27, 37, 79.4 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.09,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '63a8f9b2-b40e-4bc5-a6a5-c4500896c5b6',
        class: 'excipient',
        name: 'MCT oil',
        translations: {
            en: 'MCT oil',
            fr: 'huile TCM',
            es: 'aceite MCT',
            de: 'MCT-Öl',
            it: 'olio MCT',
            nl: 'MCT-olie',
            pt: 'óleo MCT',
            ru: 'МСТ масло',
            ja: 'MCTオイル',
            zh: 'MCT油',
            ko: 'MCT 오일',
            ar: 'زيت MCT',
            hi: 'एमसीटी तेल',
            id: 'minyak MCT',
            tr: 'MCT yağı',
            pl: 'olej MCT',
            sv: 'MCT-olja',
            da: 'MCT-olie',
            no: 'MCT-olje',
            cs: 'MCT olej',
            hu: 'MCT olaj',
            vi: 'dầu MCT'
        },
        pubchemid: null,
        self_id: 'MCT',
        molecular_weight: null,
        density: 0.942,
        viscosityArray: [ 23, 12 ],
        viscosityTempArray: [ 25, 37 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: 'fbff981e-cb82-43c6-8cc5-e29808190c82',
        class: 'excipient',
        name: 'cottonseed oil',
        translations: {
            en: 'cottonseed oil',
            fr: 'huile de coton',
            es: 'aceite de semilla de algodón',
            de: 'Baumwollsamenöl',
            it: 'olio di semi di cotone',
            nl: 'katoenzaadolie',
            pt: 'óleo de semente de algodão',
            ru: 'хлопковое масло',
            ja: '綿実油',
            zh: '棉籽油',
            ko: '면실유',
            ar: 'زيت بذور القطن',
            hi: 'कपास बीज तेल',
            id: 'minyak biji kapas',
            tr: 'pamuk tohumu yağı',
            pl: 'olej z nasion bawełny',
            sv: 'bomullsfröolja',
            da: 'bomuldsfrøolie',
            no: 'bomullsfrøolje',
            cs: 'bavlníkový olej',
            hu: 'gyapotmagolaj',
            vi: 'dầu hạt bông'
        },
        pubchemid: null,
        self_id: 'cottonseed',
        molecular_weight: null,
        density: 0.92,
        viscosityArray: [ 70 ],
        viscosityTempArray: [ 20 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '1f9a3e83-15ce-432b-a295-a5c57e4d3905',
        class: 'excipient',
        name: 'grapeseed oil',
        translations: {
            en: 'grapeseed oil',
            fr: 'huile de pépins de raisin',
            es: 'aceite de semilla de uva',
            de: 'Traubenkernöl',
            it: "olio di semi d'uva",
            nl: 'druivenpitolie',
            pt: 'óleo de semente de uva',
            ru: 'масло виноградных косточек',
            ja: 'グレープシードオイル',
            zh: '葡萄籽油',
            ko: '포도씨유',
            ar: 'زيت بذور العنب',
            hi: 'अंगूर बीज तेल',
            id: 'minyak biji anggur',
            tr: 'üzüm çekirdeği yağı',
            pl: 'olej z pestek winogron',
            sv: 'druvkärneolja',
            da: 'vindruekerneolie',
            no: 'druekjerneolje',
            cs: 'hroznový olej',
            hu: 'szőlőmagolaj',
            vi: 'dầu hạt nho'
        },
        cas_no: '8024-22-4',
        pubchemid: null,
        self_id: 'grapeseed',
        molecular_weight: null,
        density: 0.92,
        viscosityArray: [ 87.8 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: 'dd694d8a-ae87-4602-8985-d1f17b597160',
        class: 'excipient',
        name: 'arachis oil',
        translations: {
            en: 'arachis oil',
            fr: "huile d'arachide",
            es: 'aceite de cacahuete',
            de: 'Erdnussöl',
            it: 'olio di arachidi',
            nl: 'arachideolie',
            pt: 'óleo de amendoim',
            ru: 'арахисовое масло',
            ja: '落花生油',
            zh: '花生油',
            ko: '땅콩기름',
            ar: 'زيت الفول السوداني',
            hi: 'मूंगफली का तेल',
            id: 'minyak kacang tanah',
            tr: 'yer fıstığı yağı',
            pl: 'olej arachidowy',
            sv: 'jordnötsolja',
            da: 'jordnøddeolie',
            no: 'peanøttolje',
            cs: 'arašídový olej',
            hu: 'földimogyoró-olaj',
            vi: 'dầu đậu phộng'
        },
        cas_no: '8002-03-7',
        pubchemid: null,
        self_id: 'arachis',
        molecular_weight: null,
        density: 0.9372,
        viscosityArray: [ 35.2 ],
        viscosityTempArray: [ 37 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '63794584-a2e0-4395-bf18-6e25cfbe67e7',
        class: 'excipient',
        name: 'sesame oil',
        translations: {
            en: 'sesame oil',
            fr: 'huile de sésame',
            es: 'aceite de sésamo',
            de: 'Sesamöl',
            it: 'olio di sesamo',
            nl: 'sesamolie',
            pt: 'óleo de gergelim',
            ru: 'кунжутное масло',
            ja: 'ごま油',
            zh: '芝麻油',
            ko: '참기름',
            ar: 'زيت السمسم',
            hi: 'तिल का तेल',
            id: 'minyak wijen',
            tr: 'susam yağı',
            pl: 'olej sezamowy',
            sv: 'sesamolja',
            da: 'sesamolie',
            no: 'sesamolje',
            cs: 'sezamový olej',
            hu: 'szezámolaj',
            vi: 'dầu mè'
        },
        cas_no: '8008-74-0',
        pubchemid: null,
        self_id: 'sesame',
        molecular_weight: null,
        density: 0.92,
        viscosityArray: [ 45 ],
        viscosityTempArray: [ 25 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: 'd0f0d248-d9e1-4f79-aef1-3c4be7ad1cff',
        class: 'excipient',
        name: 'corn oil',
        translations: {
            en: 'corn oil',
            fr: 'huile de maïs',
            es: 'aceite de maíz',
            de: 'Maisöl',
            it: 'olio di mais',
            nl: 'maïsolie',
            pt: 'óleo de milho',
            ru: 'кукурузное масло',
            ja: 'コーン油',
            zh: '玉米油',
            ko: '옥수수유',
            ar: 'زيت الذرة',
            hi: 'मकई का तेल',
            id: 'minyak jagung',
            tr: 'mısır yağı',
            pl: 'olej kukurydziany',
            sv: 'majsolja',
            da: 'majsolie',
            no: 'maisolje',
            cs: 'kukuřičný olej',
            hu: 'kukoricaolaj',
            vi: 'dầu ngô'
        },
        cas_no: '8024-22-4',
        pubchemid: null,
        self_id: 'corn',
        molecular_weight: null,
        density: 0.92,
        viscosityArray: [ 28, 30 ],
        viscosityTempArray: [ 57, 60 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'q.s.',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null
    },
    {
        id: '63b6f358-7f94-4218-9748-4715430ca60d',
        class: 'ingredient',
        cas_no: '50-28-2',
        log_p: 3.609,
        name: 'Estradiol base',
        translations: {
            en: 'Estradiol base (β-Estradiol)',
            fr: 'Œstradiol base',
            es: 'Estradiol base',
            de: 'Estradiol Base',
            it: 'Estradiolo base',
            nl: 'Estradiol base',
            pt: 'Estradiol base',
            ru: 'Эстрадиол (основание)',
            ja: 'エストラジオール（ベース）',
            zh: '雌二醇（游离型）',
            ko: '에스트라디올 (베이스)',
            ar: 'إستراديول (الأساس)',
            hi: 'एस्ट्राडियोल (बेस)',
            id: 'Estradiol base',
            tr: 'Estradiol baz',
            pl: 'Estradiol (baza)',
            sv: 'Estradiol bas',
            da: 'Estradiol base',
            no: 'Estradiol base',
            cs: 'Estradiol báze',
            hu: 'Ösztradiol alap',
            vi: 'Estradiol dạng gốc'
        },
        pubchemid: null,
        self_id: 'estradiol_base',
        molecular_weight: 272.388,
        density: 1.0127,
        displacement: 0.89,
        melting_point: [ 175, 178 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
        blurb: '',
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3C=CC(=C4)O"
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        cas_no: '313-06-4',
        log_p: 6.14,
        name: 'Estradiol cypionate',
        translations: {
            en: 'Estradiol cypionate',
            fr: 'Œstradiol cypionate',
            es: 'Cipionato de estradiol',
            de: 'Estradiolcypionat',
            it: 'Cipionato di estradiolo',
            nl: 'Estradiolcypionaat',
            pt: 'Cipionato de estradiol',
            ru: 'Ципионат эстрадиола',
            ja: 'エストラジオールシピオン酸エステル',
            zh: '雌二醇环戊丙酸酯',
            ko: '에스트라디올 시피오네이트',
            ar: 'إستراديول سيبيونات',
            hi: 'एस्ट्राडियोल सिपियोनेट',
            id: 'Estradiol sipionat',
            tr: 'Estradiol sipiyonat',
            pl: 'Cypionian estradiolu',
            sv: 'Estradiolcypionat',
            da: 'Estradiolcypionat',
            no: 'Estradiolcypionat',
            cs: 'Estradiol cypionát',
            hu: 'Ösztradiol-cipionát',
            vi: 'Estradiol cypionate'
        },
        pubchemid: null,
        self_id: 'estradiol_cypionate',
        molecular_weight: 396.6,
        density: 1.2,
        displacement: 0.9,
        melting_point: [ 152 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
        image: null,
        mol2d: null,
        mol3d: null,
        smiles: "C[C@]12CC[C@H]3[C@@H]([C@@H]1CC[C@@H]2OC(=O)CCC4CCCC4)CCC5=CC=C(O)C=C35",
        formula: 'C26H36O3',
        blurb: `
\tEstradiol exhibits stereoisomerism, primarily due to the configuration of its hydroxyl groups and the orientation of its steroid backbone. The most biologically active form is 17beta-estradiol, where the hydroxyl group at carbon 17 is in the beta position. Its stereoisomer, 17alpha-estradiol, has the hydroxyl group in the alpha position and is significantly less potent in estrogenic activity. Additionally, estradiol can undergo glucuronidation at either the 3-hydroxyl or 17-hydroxyl positions, forming estradiol-3-glucuronide and estradiol-17-glucuronide, which are regioisomers with distinct metabolic pathways and biological roles. The benzoate esterification at the C3 hydroxyl group does not introduce additional isomerism.
\nEstradiol cypionate is a 17 alpha-cyclopentylpropinate ester of estradiol, inhibits ET-1 synthesis via estrogen receptor; IC50 value:; Target: estrogen receptor; Estradiol cypionate is a synthetic ester, is a estrogen.`,
    },
    {
        id: '6a25e544-4d0e-442c-9eae-8c0033ed51db',
        class: 'ingredient',
        cas_no: '4956-37-0',
        log_p: 7.68,
        name: 'Estradiol enanthate',
        translations: {
            en: 'Estrodial enanthate',
            fr: 'Œstradiol énanthate',
            es: 'Enantato de estradiol',
            de: 'Estradiolenantat',
            it: 'Enantato di estradiolo',
            nl: 'Estradiolenantaat',
            pt: 'Enantato de estradiol',
            ru: 'Энантат эстрадиола',
            ja: 'エストラジオールエナント酸エステル',
            zh: '雌二醇庚酸酯',
            ko: '에스트라디올 에난테이트',
            ar: 'إستراديول إينانثات',
            hi: 'एस्ट्राडियोल एनन्थेट',
            id: 'Estradiol enantat',
            tr: 'Estradiol enantat',
            pl: 'Enantan estradiolu',
            sv: 'Estradiolenantat',
            da: 'Estradiolenantat',
            no: 'Estradiolenantat',
            cs: 'Estradiol enantát',
            hu: 'Ösztradiol-enantát',
            vi: 'Estradiol enanthate'
        },
        pubchemid: null,
        self_id: 'estradiol_enanthate',
        molecular_weight: 384.56,
        density: 1.1,
        displacement: 0.9,
        melting_point: [ 94, 96 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "CCCCCCC(=O)O[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=C3C=CC(=C4)O)C"
    },

    {
        id: '4c877e8a-a3da-4457-899e-7b22527c13cc',
        class: 'ingredient',
        cas_no: '979-32-8',
        log_p: 5.3503,
        name: 'Estradiol valerate',
        translations: {
            en: 'Estrodial valerate',
            fr: "Valerate d'estradiol",
            es: 'Valerato de estradiol',
            de: 'Estradiolvalerat',
            it: 'Valerato di estradiolo',
            nl: 'Estradiolvaleraat',
            pt: 'Valerato de estradiol',
            ru: 'эстрадиола валерат',
            ja: 'エストラジオール吉草酸エステル',
            zh: '雌二醇戊酸酯',
            ko: '에스트라디올 발레레이트',
            ar: 'فاليرات إيستراديول',
            hi: 'एस्ट्राडियोल वैलेरेट',
            id: 'Estradiol valerat',
            tr: 'Estradiol valerat',
            pl: 'Walerianian estradiolu',
            sv: 'Estradiolvalerat',
            da: 'Estradiolvalerat',
            no: 'Estradiolvalerat',
            cs: 'Estradiol valerát',
            hu: 'Ösztradiol-valerát',
            vi: 'Estradiol valerate'
        },
        pubchemid: null,
        self_id: 'estradiol_valerate',
        molecular_weight: 356.4984,
        density: 1.1,
        displacement: 0.9,
        melting_point: [ 148 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
        image: null,
        mol2d: null,
        mol3d: null,
        formula: 'C23H32O3',
        smiles: 'CCCCC(=O)OC1CCC2C3CCc4cc(O)ccc4C3CCC12C'
    },
    {
        id: '0d87b9d1-5f33-4c39-bb80-ce7bd0c9fda3',
        class: 'ingredient',
        cas_no: '53-43-0',
        name: 'DHEA base',
        translations: {
            en: 'DHEA base',
            fr: 'prastérone',
            es: 'prasterona',
            de: 'Prasteron',
            it: 'prasterone',
            nl: 'prasteron',
            pt: 'prasterona',
            ru: 'прастерон',
            ja: 'プラステロン',
            zh: '普拉睾酮',
            ko: '프라스테론',
            ar: 'براستيرون',
            hi: 'प्रास्टेरोन',
            id: 'prasteron',
            tr: 'prasteron',
            pl: 'prasteron',
            sv: 'prasteron',
            da: 'prasteron',
            no: 'prasteron',
            cs: 'prasteron',
            hu: 'praszteron',
            vi: 'prasterone'
        },
        pubchemid: null,
        self_id: 'dhea_base',
        molecular_weight: 288.43,
        density: 1.05,
        displacement: 0.89,
        melting_point: [ 146, 151 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC=C4[C@@]3(CC[C@@H](C4)O)C",
    },
    {
        id: '79ae14e2-6dde-4182-abd1-f426da9a0482',
        class: 'ingredient',
        name: 'Testosterone base',
        translations: {
            en: 'testosterone base',
            fr: 'testostérone base',
            es: 'testosterona base',
            de: 'Testosteron-Base',
            it: 'testosterone base',
            nl: 'testosteronbasis',
            pt: 'testosterona base',
            ru: 'тестостероновая основа',
            ja: 'テストステロンベース',
            zh: '基础睾酮',
            ko: '테스토스테론 베이스',
            ar: 'التستوستيرون الأساسي',
            hi: 'टेस्टोस्टेरोन बेस',
            id: 'basis testosteron',
            tr: 'testosteron bazı',
            pl: 'baza testosteronu',
            sv: 'testosteronbas',
            da: 'testosteron-base',
            no: 'testosteron-base',
            cs: 'testosteron báze',
            hu: 'tesztoszteron bázis',
            vi: 'testosterone nền'
        },
        pubchemid: null,
        self_id: 'testosterone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [ 154, 155 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.75,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: '58-22-0',
        smiles: "O[C@H]1CC[C@@]2([H])[C@]3([H])CCC4=CC(CC[C@]4(C)[C@@]3([H])CC[C@@]21C)=O",
    },
    {
        id: '3284e1f4-cd79-4fd0-973b-f154d22f706e',
        class: 'ingredient',
        name: 'Testosterone acetate',
        translations: {
            en: 'testosterone acetate',
            fr: 'acétate de testostérone',
            es: 'acetato de testosterona',
            de: 'Testosteronacetat',
            it: 'acetato di testosterone',
            nl: 'testosteronacetaat',
            pt: 'acetato de testosterona',
            ru: 'ацетат тестостерона',
            ja: 'テストステロン酢酸エステル',
            zh: '醋酸睾酮',
            ko: '테스토스테론 아세테이트',
            ar: 'أسيتات التستوستيرون',
            hi: 'टेस्टोस्टेरोन एसीटेट',
            id: 'testosteron asetat',
            tr: 'testosteron asetat',
            pl: 'octan testosteronu',
            sv: 'testosteronacetat',
            da: 'testosteronacetat',
            no: 'testosteronacetat',
            cs: 'testosteron acetát',
            hu: 'tesztoszteron-acetát',
            vi: 'testosterone acetate'
        },
        pubchemid: null,
        self_id: 'testosterone_acetate',
        molecular_weight: 330.4611,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [ 140, 144 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
        cas_no: '1045-69-8',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 4.45,
        formula: 'C21H30O3',
        smiles: 'CC(=O)OC1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C'
    },
    {
        id: '5e9333a6-3779-4443-b004-0d7338efd2fc',
        class: 'ingredient',
        name: 'Testosterone isocaproate',
        translations: {
            en: 'testosterone isocaproate',
            fr: 'isocaproate de testostérone',
            es: 'isocaproato de testosterona',
            de: 'Testosteronisocaproat',
            it: 'isocaproato di testosterone',
            nl: 'testosteronisocaproaat',
            pt: 'isocaproato de testosterona',
            ru: 'изокапроат тестостерона',
            ja: 'テストステロンイソカプロン酸エステル',
            zh: '异己酸睾酮',
            ko: '테스토스테론 이소카프로에이트',
            ar: 'إيزوكابروات التستوستيرون',
            hi: 'टेस्टोस्टेरोन आइसोकैप्रोएट',
            id: 'testosteron isokaproat',
            tr: 'testosteron izokaproat',
            pl: 'izokapronian testosteronu',
            sv: 'testosteronisokaproat',
            da: 'testosteronisokaproat',
            no: 'testosteronisokaproat',
            cs: 'testosteron isokaproát',
            hu: 'tesztoszteron-izokaproát',
            vi: 'testosterone isocaproate'
        },
        cas_no: '15262-86-9',
        pubchemid: null,
        self_id: 'testosterone_isocaproate',
        molecular_weight: 386.57,
        density: 1.07,
        displacement: 0.89,
        melting_point: [ 79, 81 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "CC(C)CCC(=O)OC1CCC2C1(CCC3C2CCC4=CC(=O)CCC34C)C",
    },
    {
        id: 'da9daed2-44d8-4a7c-9dfd-981f069f3da5',
        class: 'ingredient',
        name: 'Testosterone propionate',
        translations: {
            en: 'testosterone propionate',
            fr: 'propionate de testostérone',
            es: 'propionato de testosterona',
            de: 'Testosteronpropionat',
            it: 'propionato di testosterone',
            nl: 'testosteronpropionaat',
            pt: 'propionato de testosterona',
            ru: 'пропионат тестостерона',
            ja: 'テストステロンプロピオン酸エステル',
            zh: '丙酸睾酮',
            ko: '테스토스테론 프로피오네이트',
            ar: 'بروبيونات التستوستيرون',
            hi: 'टेस्टोस्टेरोन प्रोपियोनेट',
            id: 'testosteron propionat',
            tr: 'testosteron propiyonat',
            pl: 'propionian testosteronu',
            sv: 'testosteronpropionat',
            da: 'testosteronpropionat',
            no: 'testosteronpropionat',
            cs: 'testosteron propionát',
            hu: 'tesztoszteron-propionát',
            vi: 'testosterone propionate'
        },
        pubchemid: null,
        self_id: 'testosterone_propionate',
        molecular_weight: 344.4877,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 118, 122 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.67,
        cas_no: '57-85-2',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 4.8401,
        formula: 'C22H32O3',
        smiles: 'CCC(=O)OC1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C'
    },
    {
        id: '45f4099a-7695-4c67-a763-49621b028712',
        class: 'ingredient',
        name: 'Testosterone phenylpropionate',
        translations: {
            en: 'testosterone phenylpropionate',
            fr: 'phénylpropionate de testostérone',
            es: 'fenilpropionato de testosterona',
            de: 'Testosteronphenylpropionat',
            it: 'fenilpropionato di testosterone',
            nl: 'testosteronfenylpropionaat',
            pt: 'fenilpropionato de testosterona',
            ru: 'фенилпропионат тестостерона',
            ja: 'テストステロンフェニルプロピオン酸エステル',
            zh: '苯丙酸睾酮',
            ko: '테스토스테론 페닐프로피오네이트',
            ar: 'فينيل بروبيونات التستوستيرون',
            hi: 'टेस्टोस्टेरोन फेनिलप्रोपियोनेट',
            id: 'testosteron fenilpropionat',
            tr: 'testosteron fenilpropiyonat',
            pl: 'fenylopropionian testosteronu',
            sv: 'testosteronfenylpropionat',
            da: 'testosteronfenylpropionat',
            no: 'testosteronfenylpropionat',
            cs: 'testosteron fenylpropionát',
            hu: 'tesztoszteron-fenilpropionát',
            vi: 'testosterone phenylpropionate'
        },
        pubchemid: null,
        self_id: 'testosterone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        melting_point: [ 115, 116 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: '1255-49-8',
        smiles: "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2OC(=O)CCC4=CC=CC=C4)CCC5=CC(=O)CC[C@]35C"
    },
    {
        id: 'ece861d0-56f0-4c7f-a0db-0306f4a815ff',
        class: 'ingredient',
        name: 'Testosterone cypionate',
        translations: {
            en: 'testosterone cypionate',
            fr: 'cypionate de testostérone',
            es: 'cipionato de testosterona',
            de: 'Testosteroncipionat',
            it: 'cipionato di testosterone',
            nl: 'testosteroncypionaat',
            pt: 'cipionato de testosterona',
            ru: 'ципионат тестостерона',
            ja: 'テストステロンシピオン酸エステル',
            zh: '环戊丙酸睾酮',
            ko: '테스토스테론 사이피오네이트',
            ar: 'سيبيونات التستوستيرون',
            hi: 'टेस्टोस्टेरोन सिपियोनेट',
            id: 'testosteron sipionat',
            tr: 'testosteron sipiyonat',
            pl: 'cypionian testosteronu',
            sv: 'testosteroncipionat',
            da: 'testosteroncipionat',
            no: 'testosteroncipionat',
            cs: 'testosteron cypionát',
            hu: 'tesztoszteron-cipionát',
            vi: 'testosterone cypionate'
        },
        pubchemid: null,
        self_id: 'testosterone_cypionate',
        molecular_weight: 412.6047,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 98, 102 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.84,
        cas_no: '58-20-8',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 6.4005,
        formula: 'C27H40O3',
        smiles: 'CC12CCC(=O)C=C1CCC1C2CCC2(C)C(OC(=O)CCC3CCCC3)CCC12',
        blurb: `Testosterone
Cypionate, USP which is the oil-soluble 17 (beta)- cyclopentylpropionate ester of the
androgenic hormone testosterone.
Testosterone Cypionate, USP is a white or creamy white crystalline powder, odorless or
nearly so and stable in air. It is insoluble in water, freely soluble in alcohol, chloroform,
dioxane, ether, and soluble in vegetable oils.
The chemical name for Testosterone Cypionate, USP is androst-4-en-3-one,17-(3-
cyclopentyl-1- oxopropoxy)-, (17β)-. `
    },
    {
        id: '8168e858-9e39-4b57-a7c5-400b4d54564d',
        class: 'ingredient',
        name: 'Testosterone enanthate',
        translations: {
            en: 'testosterone enanthate',
            fr: 'énanthate de testostérone',
            es: 'enantato de testosterona',
            de: 'Testosteronenanthat',
            it: 'enantato di testosterone',
            nl: 'testosteronenanthaat',
            pt: 'enantato de testosterona',
            ru: 'энантат тестостерона',
            ja: 'テストステロンエナント酸エステル',
            zh: '庚酸睾酮',
            ko: '테스토스테론 에난테이트',
            ar: 'إينونثات التستوستيرون',
            hi: 'टेस्टोस्टेरोन एनन्थेट',
            id: 'testosteron enantat',
            tr: 'testosteron enantat',
            pl: 'enantan testosteronu',
            sv: 'testosteronenantat',
            da: 'testosteronenantat',
            no: 'testosteronenantat',
            cs: 'testosteron enantát',
            hu: 'tesztoszteron-enantát',
            vi: 'testosterone enanthate'
        },
        pubchemid: null,
        self_id: 'testosterone_enanthate',
        molecular_weight: 400.594,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [ 32, 36 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.75,
        cas_no: '315-37-7',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 6.4005,
        formula: 'C26H40O3',
        smiles: 'CCCCCCC(=O)OC1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C'
    },
    {
        id: 'eff38ba2-f886-4016-b173-c490fffe8026',
        class: 'ingredient',
        name: 'Testosterone decanoate',
        translations: {
            en: 'testosterone decanoate',
            fr: 'décanoate de testostérone',
            es: 'decanoato de testosterona',
            de: 'Testosterondekanoat',
            it: 'decanoato di testosterone',
            nl: 'testosterondecanoaat',
            pt: 'decanoato de testosterona',
            ru: 'деканоат тестостерона',
            ja: 'テストステロンデカン酸エステル',
            zh: '癸酸睾酮',
            ko: '테스토스테론 데카노에이트',
            ar: 'ديكانوات التستوستيرون',
            hi: 'टेस्टोस्टेरोन डिकानोएट',
            id: 'testosteron dekanoat',
            tr: 'testosteron dekanoat',
            pl: 'dekanian testosteronu',
            sv: 'testosterondekanoat',
            da: 'testosterondekanoat',
            no: 'testosterondekanoat',
            cs: 'testosteron dekanoát',
            hu: 'tesztoszteron-dekanoát',
            vi: 'testosterone decanoate'
        },
        pubchemid: null,
        self_id: 'testosterone_decanoate',
        molecular_weight: 442.6737,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [ 47, 49 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 300,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.78,
        cas_no: '5721-91-5',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 7.570799999999999,
        formula: 'C29H46O3',
        smiles: 'CCCCCCCCCC(=O)OC1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C'
    },
    {
        id: '0f49f736-d65e-49a0-8013-327920701451',
        class: 'ingredient',
        name: 'Testosterone undecanoate',
        translations: {
            en: 'testosterone undecanoate',
            fr: 'undécanoate de testostérone',
            es: 'undecanoato de testosterona',
            de: 'Testosteronundekanoat',
            it: 'undecanoato di testosterone',
            nl: 'testosteronundecanoaat',
            pt: 'undecanoato de testosterona',
            ru: 'ундеканоат тестостерона',
            ja: 'テストステロンウンデカン酸エステル',
            zh: '十一酸睾酮',
            ko: '테스토스테론 운데카노에이트',
            ar: 'أنديكانوات التستوستيرون',
            hi: 'टेस्टोस्टेरोन अंडेकानोएट',
            id: 'testosteron undecanoat',
            tr: 'testosteron undekanoat',
            pl: 'undekanian testosteronu',
            sv: 'testosteronundekanoat',
            da: 'testosteronundekanoat',
            no: 'testosteronundekanoat',
            cs: 'testosteron undekanoát',
            hu: 'tesztoszteron-undekanoát',
            vi: 'testosterone undecanoate'
        },
        pubchemid: null,
        self_id: 'testosterone_undecanoate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        melting_point: [ 59, 61 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.78,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: '5949-44-0',
        smiles: "CCCCCCCCCCC(=O)O[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=CC(=O)CC[C@]34C)C"
    },
    {
        id: '4a75c259-e3ee-4ed9-a263-db72938cec3e',
        class: 'ingredient',
        name: 'Trenbolone base',
        translations: {
            en: 'trenbolone base',
            fr: 'trenbolone base',
            es: 'trenbolona base',
            de: 'Trenbolon-Base',
            it: 'trenbolone base',
            nl: 'trenbolonbasis',
            pt: 'trenbolona base',
            ru: 'основа тренболона',
            ja: 'トレンボロンベース',
            zh: '群勃龙基础粉',
            ko: '트렌볼론 베이스',
            ar: 'قاعدة ترينبولون',
            hi: 'ट्रेनबोलोन बेस',
            id: 'basis trenbolon',
            tr: 'trenbolon bazı',
            pl: 'baza trenbolonu',
            sv: 'trenbolonbas',
            da: 'trenbolon-base',
            no: 'trenbolon-base',
            cs: 'trenbolon báze',
            hu: 'trenbolon bázis',
            vi: 'trenbolone nền'
        },
        pubchemid: null,
        self_id: 'trenbolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [ 168, 172 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.7,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "10161-33-8",
        smiles: "O=C4\\C=C2/C(=C1/C=C\\[C@@]3([C@@H](O)CC[C@H]3[C@@H]1CC2)C)CC4",
    },
    {
        id: '72b9a6b8-c6a5-4a70-8466-dc5fa470c9da',
        class: 'ingredient',
        name: 'Trenbolone acetate',
        translations: {
            en: 'trenbolone acetate',
            fr: 'acétate de trenbolone',
            es: 'acetato de trenbolona',
            de: 'Trenbolonacetat',
            it: 'acetato di trenbolone',
            nl: 'trenbolonacetaat',
            pt: 'acetato de trenbolona',
            ru: 'ацетат тренболона',
            ja: 'トレンボロン酢酸エステル',
            zh: '醋酸群勃龙',
            ko: '트렌볼론 아세테이트',
            ar: 'أسيتات ترينبولون',
            hi: 'ट्रेनबोलोन एसीटेट',
            id: 'trenbolon asetat',
            tr: 'trenbolon asetat',
            pl: 'octan trenbolonu',
            sv: 'trenbolonacetat',
            da: 'trenbolonacetat',
            no: 'trenbolonacetat',
            cs: 'trenbolon acetát',
            hu: 'trenbolon-acetát',
            vi: 'trenbolone acetate'
        },
        pubchemid: null,
        self_id: 'trenbolone_acetate',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [ 140, 144 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.6,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "10161-34-9",
        smiles: "CC(=O)O[C@H]1CC[C@@H]2[C@@]1(C=CC3=C4CCC(=O)C=C4CC[C@@H]23)C",
    },
    {
        id: '047a7265-471a-4cb9-900c-05d810c66d06',
        class: 'ingredient',
        name: 'Trenbolone hexahydrobenzylcarbonate',
        translations: {
            en: 'trenbolone hexahydrobenzylcarbonate',
            fr: 'hexahydrobenzylcarbonate de trenbolone',
            es: 'hexahidrobencilcarbonato de trenbolona',
            de: 'Trenbolonhexahydrobenzylcarbonat',
            it: 'esaidrobenzilcarbonato di trenbolone',
            nl: 'trenbolonhexahydrobenzylcarbonaat',
            pt: 'hexahidrobenzilcarbonato de trenbolona',
            ru: 'гексагидробензилкарбонат тренболона',
            ja: 'トレンボロンヘキサヒドロベンジルカーボネート',
            zh: '己氢苄基碳酸群勃龙酯',
            ko: '트렌볼론 헥사하이드로벤질카보네이트',
            ar: 'هكسا هيدروبنزيل كربونات ترينبولون',
            hi: 'ट्रेनबोलोन हेक्साहाइड्रोबेंज़िलकार्बोनेट',
            id: 'trenbolon heksahidrobenzilkarbonat',
            tr: 'trenbolon hekzahidrobenzilkarbonat',
            pl: 'heksahydrobenzylowęglan trenbolonu',
            sv: 'trenbolonhexahydrobensylkarbonat',
            da: 'trenbolonhexahydrobenzylcarbonat',
            no: 'trenbolonhexahydrobenzylkarbonat',
            cs: 'trenbolon hexahydrobenzylkarbonát',
            hu: 'trenbolon-hexahidrobenzilkarbonát',
            vi: 'trenbolone hexahydrobenzylcarbonate'
        },
        pubchemid: null,
        self_id: 'trenbolone_hexahydrobenzylcarbonate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 183, 186 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 75,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 9,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "23454-33-3",
        smiles: "C[C@]12C=CC3=C4CCC(=O)C=C4CC[C@H]3[C@@H]1CC[C@@H]2OC(=O)OCC5CCCCC5"
    },
    {
        id: '7755627f-59e6-4967-8088-ff833284832c',
        class: 'ingredient',
        name: 'Trenbolone enanthate',
        translations: {
            en: 'trenbolone enanthate',
            fr: 'énanthate de trenbolone',
            es: 'enantato de trenbolona',
            de: 'Trenbolonenanthat',
            it: 'enantato di trenbolone',
            nl: 'trenbolonenanthaat',
            pt: 'enantato de trenbolona',
            ru: 'энантат тренболона',
            ja: 'トレンボロンエナント酸エステル',
            zh: '庚酸群勃龙',
            ko: '트렌볼론 에난테이트',
            ar: 'إينونثات ترينبولون',
            hi: 'ट्रेनबोलोन एनन्थेट',
            id: 'trenbolon enantat',
            tr: 'trenbolon enantat',
            pl: 'enantan trenbolonu',
            sv: 'trenbolonenantat',
            da: 'trenbolonenantat',
            no: 'trenbolonenantat',
            cs: 'trenbolon enantát',
            hu: 'trenbolon-enantát',
            vi: 'trenbolone enanthate'
        },
        pubchemid: null,
        self_id: 'trenbolone_enanthate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 72, 78 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "CCCCCCC(=O)O[C@H]1CC[C@@H]2[C@@]1(C=CC3=C4CCC(=O)C=C4CC[C@@H]23)C",
        cas_no: "1629618-98-9",
    },
    {
        id: '68cb85a2-8fe0-4e76-bf33-8a0016e33297',
        class: 'ingredient',
        name: 'Drostanolone propionate',
        translations: {
            en: 'drostanolone propionate',
            fr: 'propionate de drostanolone',
            es: 'propionato de drostanolona',
            de: 'Drostanolonpropionat',
            it: 'propionato di drostanolone',
            nl: 'drostanolonpropionaat',
            pt: 'propionato de drostanolona',
            ru: 'пропионат дростанолона',
            ja: 'ドロスタノロンプロピオン酸エステル',
            zh: '丙酸屈他雄酮',
            ko: '드로스타놀론 프로피오네이트',
            ar: 'بروبيونات دروستانولون',
            hi: 'ड्रोस्टानोलोन प्रोपियोनेट',
            id: 'drostanolon propionat',
            tr: 'drostanolon propiyonat',
            pl: 'propionian drostanolonu',
            sv: 'drostanolonpropionat',
            da: 'drostanolonpropionat',
            no: 'drostanolonpropionat',
            cs: 'drostanolon propionát',
            hu: 'drosztanolon-propionát',
            vi: 'drostanolone propionate'
        },
        pubchemid: null,
        self_id: 'drostanolone_propionate',
        molecular_weight: 360.5301,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [ 125, 127 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
        cas_no: '521-12-0',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 5.1659999999999995,
        formula: 'C23H36O3',
        smiles: 'CCC(=O)O[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC[C@@H]4[C@@]3(C[C@H](C(=O)C4)C)C)C',
        cas_no: '58-19-5',
    },
    {
        id: 'fd5ea43b-5ac1-475b-b97c-07550abb35e6',
        class: 'ingredient',
        name: 'Drostanolone enanthate',
        translations: {
            en: 'drostanolone enanthate',
            fr: 'énanthate de drostanolone',
            es: 'enantato de drostanolona',
            de: 'Drostanolonenanthat',
            it: 'enantato di drostanolone',
            nl: 'drostanolonenantaat',
            pt: 'enantato de drostanolona',
            ru: 'энантат дростанолона',
            ja: 'ドロスタノロンエナント酸エステル',
            zh: '庚酸屈他雄酮',
            ko: '드로스타놀론 에난테이트',
            ar: 'إينونثات دروستانولون',
            hi: 'ड्रोस्टानोलोन एनन्थेट',
            id: 'drostanolon enantat',
            tr: 'drostanolon enantat',
            pl: 'enantan drostanolonu',
            sv: 'drostanolonenantat',
            da: 'drostanolonenantat',
            no: 'drostanolonenantat',
            cs: 'drostanolon enantát',
            hu: 'drosztanolon-enantát',
            vi: 'drostanolone enanthate'
        },
        pubchemid: null,
        self_id: 'drostanolone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [ 53, 56 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.7,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "58-19-5",
        smiles: "CCCCCCC(=O)OC1CCC2C1(CCC3C2CCC4C3(CC(C(=O)C4)C)C)",
    },
    {
        id: '4752c7f2-858a-4b94-b2c6-344eba7e1820',
        class: 'ingredient',
        name: 'Methenolone acetate',
        translations: {
            en: 'methenolone acetate',
            fr: 'acétate de méthénolone',
            es: 'acetato de metenolona',
            de: 'Methenolonacetat',
            it: 'acetato di metenolone',
            nl: 'methenolonacetaat',
            pt: 'acetato de metenolona',
            ru: 'ацетат метенолона',
            ja: 'メテノロン酢酸エステル',
            zh: '醋酸美替诺龙',
            ko: '메테놀론 아세테이트',
            ar: 'أسيتات ميثينولون',
            hi: 'मेथेनोलोन एसीटेट',
            id: 'metenolon asetat',
            tr: 'metenolon asetat',
            pl: 'octan metenolonu',
            sv: 'methenolonacetat',
            da: 'methenolonacetat',
            no: 'methenolonacetat',
            cs: 'methenolon acetát',
            hu: 'metenolon-acetát',
            vi: 'methenolone acetate'
        },
        pubchemid: null,
        self_id: 'methenolone_acetate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 141, 143 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 15,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "434-05-9",
        smiles: "CCC1=CC(=O)C[C@H]2[C@]1([C@H]3CC[C@]4([C@H]([C@@H]3CC2)CC[C@@H]4OC(=O)C)C)C",
    },
    {
        id: 'b4cb05ee-2365-441b-ac96-da019f94b101',
        class: 'ingredient',
        name: 'Methenolone enanthate',
        translations: {
            en: 'methenolone enanthate',
            fr: 'énanthate de méthénolone',
            es: 'enantato de metenolona',
            de: 'Methenolonenanthat',
            it: 'enantato di metenolone',
            nl: 'methenolonenantaat',
            pt: 'enantato de metenolona',
            ru: 'энантат метенолона',
            ja: 'メテノロンエナント酸エステル',
            zh: '庚酸美替诺龙',
            ko: '메테놀론 에난테이트',
            ar: 'إينونثات ميثينولون',
            hi: 'मेथेनोलोन एनन्थेट',
            id: 'metenolon enantat',
            tr: 'metenolon enantat',
            pl: 'enantan metenolonu',
            sv: 'methenolonenantat',
            da: 'methenolonenantat',
            no: 'methenolonenantat',
            cs: 'methenolon enantát',
            hu: 'metenolon-enantát',
            vi: 'methenolone enanthate'
        },
        pubchemid: null,
        self_id: 'methenolone_enanthate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        melting_point: [ 66, 71 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 15,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "303-42-4",
        smiles: 'C[C@@]12[C@@]3([C@]([C@]4([C@](C)(CC3)[C@@H](OC(CCCCCC)=O)CC4)[H])(CC[C@]1(CC(=O)C=C2C)[H])[H])[H]',
    },
    {
        id: '399e0988-8ae4-4910-abb7-463202f38aad',
        class: 'ingredient',
        name: 'Nandrolone base',
        translations: {
            en: 'nandrolone base',
            fr: 'nandrolone base',
            es: 'nandrolona base',
            de: 'Nandrolon-Base',
            it: 'nandrolone base',
            nl: 'nandrolonbasis',
            pt: 'nandrolona base',
            ru: 'основа нандролона',
            ja: 'ナンドロロンベース',
            zh: '诺龙基础粉',
            ko: '난드롤론 베이스',
            ar: 'قاعدة ناندرولون',
            hi: 'नैंड्रोलोन बेस',
            id: 'basis nandrolon',
            tr: 'nandrolon bazı',
            pl: 'baza nandrolonu',
            sv: 'nandrolonbas',
            da: 'nandrolon-base',
            no: 'nandrolon-base',
            cs: 'nandrolon báze',
            hu: 'nandrolon bázis',
            vi: 'nandrolone nền'
        },
        pubchemid: null,
        self_id: 'nandrolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [ 120, 125 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "434-22-0",
        smiles: "O=C4\\C=C2/[C@@H]([C@H]1CC[C@@]3([C@@H](O)CC[C@H]3[C@@H]1CC2)C)CC4"
    },
    {
        id: '6dddc9bc-d543-46bb-b0b4-91c0e9dc4d85',
        class: 'ingredient',
        name: 'Nandrolone phenylpropionate',
        translations: {
            en: 'nandrolone phenylpropionate',
            fr: 'phénylpropionate de nandrolone',
            es: 'fenilpropionato de nandrolona',
            de: 'Nandrolonphenylpropionat',
            it: 'fenilpropionato di nandrolone',
            nl: 'nandrolonfenylpropionaat',
            pt: 'fenilpropionato de nandrolona',
            ru: 'фенилпропионат нандролона',
            ja: 'ナンドロロンフェニルプロピオン酸エステル',
            zh: '苯丙酸诺龙',
            ko: '난드롤론 페닐프로피오네이트',
            ar: 'فينيل بروبيونات ناندرولون',
            hi: 'नैंड्रोलोन फेनिलप्रोपियोनेट',
            id: 'nandrolon fenilpropionat',
            tr: 'nandrolon fenilpropiyonat',
            pl: 'fenylopropionian nandrolonu',
            sv: 'nandrolonfenylpropionat',
            da: 'nandrolonfenylpropionat',
            no: 'nandrolonfenylpropionat',
            cs: 'nandrolon fenylpropionát',
            hu: 'nandrolon-fenilpropionát',
            vi: 'nandrolone phenylpropionate'
        },
        pubchemid: null,
        self_id: 'nandrolone_phenylpropionate',
        molecular_weight: 406.5571,
        density: 1.1363636363636365,
        displacement: 0.88,
        melting_point: [ 85, 87 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.25,
        cas_no: '62-90-8',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 5.6728000000000005,
        formula: 'C27H34O3',
        smiles: 'CC12CCC3C4CCC(=O)C=C4CCC3C1CCC2OC(=O)CCc1ccccc1'
    },
    {
        id: 'b52f1491-f0bb-4c6d-aab5-a01c9fdc5d9c',
        class: 'ingredient',
        name: 'Nandrolone decanoate',
        translations: {
            en: 'nandrolone decanoate',
            fr: 'décanoate de nandrolone',
            es: 'decanoato de nandrolona',
            de: 'Nandrolondekanoat',
            it: 'decanoato di nandrolone',
            nl: 'nandrolondecanoaat',
            pt: 'decanoato de nandrolona',
            ru: 'деканоат нандролона',
            ja: 'ナンドロロンデカン酸エステル',
            zh: '癸酸诺龙',
            ko: '난드롤론 데카노에이트',
            ar: 'ديكانوات ناندرولون',
            hi: 'नैंड्रोलोन डिकानोएट',
            id: 'nandrolon dekanoat',
            tr: 'nandrolon dekanoat',
            pl: 'dekanian nandrolonu',
            sv: 'nandrolondekanoat',
            da: 'nandrolondekanoat',
            no: 'nandrolondekanoat',
            cs: 'nandrolon dekanoát',
            hu: 'nandrolon-dekanoát',
            vi: 'nandrolone decanoate'
        },
        pubchemid: null,
        self_id: 'nandrolone_decanoate',
        molecular_weight: 428.63,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [ 30, 35 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0.92,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "360-70-3",
        smiles: "CCCCCCCCCC(=O)O[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=CC(=O)CC[C@H]34)C"
    },
    {
        id: 'df72bcfe-9b4b-44b6-bad5-745f53bae410',
        class: 'ingredient',
        name: 'Boldenone base',
        cas_no: '846-48-0',
        log_p: 2.3,
        translations: {
            en: 'boldenone base',
            fr: 'boldénone base',
            es: 'boldenona base',
            de: 'Boldenon-Base',
            it: 'boldenone base',
            nl: 'boldenonbasis',
            pt: 'boldenona base',
            ru: 'основа болденона',
            ja: 'ボルデノンベース',
            zh: '博尔德酮基础粉',
            ko: '볼데논 베이스',
            ar: 'قاعدة بولدينون',
            hi: 'बोल्डेनोन बेस',
            id: 'basis boldenon',
            tr: 'boldenon bazı',
            pl: 'baza boldenonu',
            sv: 'boldenonbas',
            da: 'boldenon-base',
            no: 'boldenon-base',
            cs: 'boldenon báze',
            hu: 'boldenon bázis',
            vi: 'boldenone nền'
        },
        pubchemid: null,
        self_id: 'boldenone_base',
        molecular_weight: 286.4,
        density: 1.14,
        displacement: 0.91,
        melting_point: [ 168.1 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "846-48-0",
        smiles: "O=C\\1\\C=C/[C@]4(/C(=C/1)CC[C@@H]2[C@@H]4CC[C@@]3([C@@H](O)CC[C@@H]23)C)C"
    },
    {
        id: 'ddb94505-0cc0-4d4a-a183-ef1cfd79c36b',
        class: 'ingredient',
        name: 'Boldenone acetate',
        cas_no: '2363-59-9',
        log_p: 4.39,
        translations: {
            en: 'boldenone acetate',
            fr: 'acétate de boldénone',
            es: 'acetato de boldenona',
            de: 'Boldenonacetat',
            it: 'acetato di boldenone',
            nl: 'boldenonacetaat',
            pt: 'acetato de boldenona',
            ru: 'ацетат болденона',
            ja: 'ボルデノンアセテート',
            zh: '醋酸博尔德酮',
            ko: '볼데논 아세테이트',
            ar: 'أسيتات بولدينون',
            hi: 'बोल्डेनोन एसीटेट',
            id: 'boldenon asetat',
            tr: 'boldenon asetat',
            pl: 'octan boldenonu',
            sv: 'boldenonacetat',
            da: 'boldenonacetat',
            no: 'boldenonacetat',
            cs: 'boldenon acetát',
            hu: 'boldenon-acetát',
            vi: 'boldenone acetate'
        },
        pubchemid: null,
        self_id: 'boldenone_acetate',
        molecular_weight: 328.4,
        density: 1.1,
        displacement: 0.95,
        melting_point: [ 0 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.65,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "2363-59-9",
        smiles: "CC(=O)O[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=CC(=O)C=C[C@]34C)C"
    },
    {
        id: '2c6f2343-7b68-4e03-a39b-4a36759fac72',
        class: 'ingredient',
        name: 'Boldenone undecylenate',
        cas_no: '13103-34-9',
        log_p: 3.1,
        translations: {
            en: 'boldenone undecylenate',
            fr: 'undécylénate de boldénone',
            es: 'undecilenato de boldenona',
            de: 'Boldenonundecylenat',
            it: 'undecilenato di boldenone',
            nl: 'boldenonundecyleenaat',
            pt: 'undecilenato de boldenona',
            ru: 'ундесиленат болденона',
            ja: 'ボルデノンウンデシレン酸エステル',
            zh: '十一烯酸博尔德酮',
            ko: '볼데논 운데실레네이트',
            ar: 'أنديسيلينات بولدينون',
            hi: 'बोल्डेनोन अन्डेसिलिनेट',
            id: 'boldenon undecilenat',
            tr: 'boldenon undesilenat',
            pl: 'undecylenian boldenonu',
            sv: 'boldenonundecylenat',
            da: 'boldenonundecylenat',
            no: 'boldenonundecylenat',
            cs: 'boldenon undecylenát',
            hu: 'boldenon-undecilénát',
            vi: 'boldenone undecylenate'
        },
        pubchemid: null,
        self_id: 'boldenone_undecylenate',
        molecular_weight: 452.67,
        density: 1.055,
        displacement: 0.95,
        melting_point: [ 0 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.65,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: '13103-34-9',
        smiles: "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2OC(=O)CCCCCCCCC=C)CCC4=CC(=O)C=C[C@]34C"
    },
    {
        id: 'f5e27888-09c2-4c3f-aed6-dd990b269f86',
        class: 'ingredient',
        name: 'Dihydroboldenone cypionate',
        translations: {
            en: 'dihydroboldenone cypionate',
            fr: 'cypionate de dihydroboldénone',
            es: 'cipionato de dihidroboldenona',
            de: 'Dihydroboldenoncypionat',
            it: 'cipionato di diidroboldenone',
            nl: 'dihydroboldenoncypionaat',
            pt: 'cipionato de dihidroboldenona',
            ru: 'ципионат дигидроболденона',
            ja: 'ジヒドロボルデノンシピオン酸エステル',
            zh: '环戊丙酸二氢博尔德酮',
            ko: '디하이드로볼데논 사이피오네이트',
            ar: 'سيبيونات ديهدروبوليينون',
            hi: 'डाइहाइड्रोबोल्डेनोन सिपियोनेट',
            id: 'dihidroboldenon sipionat',
            tr: 'dihidroboldenon sipiyonat',
            pl: 'cypionian dihydroboldenonu',
            sv: 'dihydroboldenoncypionat',
            da: 'dihydroboldenoncypionat',
            no: 'dihydroboldenoncypionat',
            cs: 'dihydroboldenon cypionát',
            hu: 'dihidroboldenon-cipionát',
            vi: 'dihydroboldenone cypionate'
        },
        pubchemid: null,
        self_id: 'dihydroboldenone_cypionate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        melting_point: [ 192, 196 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "65-06-5",
        smiles: "C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2OC(=O)CCC4CCCC4)CCC5=CC(=O)C=C[C@]35C"

    },
    {
        id: 'da580482-09ce-42c4-849f-475ca978ba52',
        class: 'ingredient',
        name: 'Dianabol',
        cas_no: '41235-52-3',
        log_p: 5.9045000000000005,
        translations: {
            en: 'Dianabol',
            fr: 'Dianabol',
            es: 'Dianabol',
            de: 'Dianabol',
            it: 'Dianabol',
            nl: 'Dianabol',
            pt: 'Dianabol',
            ru: 'Дианабол',
            ja: 'ダイアナボル',
            zh: '大力补',
            ko: '다이아나볼',
            ar: 'ديانابول',
            hi: 'डायनाबोल',
            id: 'Dianabol',
            tr: 'Dianabol',
            pl: 'Dianabol',
            sv: 'Dianabol',
            da: 'Dianabol',
            no: 'Dianabol',
            cs: 'Dianabol',
            hu: 'Dianabol',
            vi: 'Dianabol'
        },
        pubchemid: null,
        self_id: 'dianabol',
        molecular_weight: 372.6162,
        density: 1.075268817204301,
        displacement: 0.93,
        melting_point: [ 164, 167 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
        image: null,
        mol2d: null,
        mol3d: null,
        formula: 'C23H36O2Si',
        smiles: 'CC12C=CC(=O)C=C1CCC1C2CCC2(C)C1CCC2(C)O[Si](C)(C)C'
    },
    {
        id: 'a651545a-94f7-4c5c-b123-56b332e61b6f',
        class: 'ingredient',
        name: 'Anadrol',
        cas_no: '434-07-1',
        log_p: 4.401,
        translations: {
            en: 'Anadrol',
            fr: 'Anadrol',
            es: 'Anadrol',
            de: 'Anadrol',
            it: 'Anadrol',
            nl: 'Anadrol',
            pt: 'Anadrol',
            ru: 'Анадрол',
            ja: 'アナドロール',
            zh: '康力龙',
            ko: '아나드롤',
            ar: 'أنادرول',
            hi: 'एनाड्रोल',
            id: 'Anadrol',
            tr: 'Anadrol',
            pl: 'Anadrol',
            sv: 'Anadrol',
            da: 'Anadrol',
            no: 'Anadrol',
            cs: 'Anadrol',
            hu: 'Anadrol',
            vi: 'Anadrol'
        },
        pubchemid: null,
        self_id: 'anadrol',
        molecular_weight: 332.477,
        density: 1.1627906976744187,
        displacement: 0.86,
        melting_point: [ 177, 180 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.98,
        image: null,
        mol2d: null,
        mol3d: null,
        formula: 'C21H32O3',
        smiles: 'CC12CC(=CO)C(=O)CC1CCC1C2CCC2(C)C1CCC2(C)O'
    },
    {
        id: '43324ec5-de4b-4f37-ba26-516fed3fc1c4',
        class: 'ingredient',
        name: 'Anavar',
        translations: {
            en: 'Anavar',
            fr: 'Anavar',
            es: 'Anavar',
            de: 'Anavar',
            it: 'Anavar',
            nl: 'Anavar',
            pt: 'Anavar',
            ru: 'Анавар',
            ja: 'アナバー',
            zh: '安纳瓦',
            ko: '아나바',
            ar: 'أنافار',
            hi: 'एनावर',
            id: 'Anavar',
            tr: 'Anavar',
            pl: 'Anavar',
            sv: 'Anavar',
            da: 'Anavar',
            no: 'Anavar',
            cs: 'Anavar',
            hu: 'Anavar',
            vi: 'Anavar'
        },
        pubchemid: null,
        self_id: 'anavar',
        molecular_weight: 306.4397,
        density: 1.1111111111111112,
        displacement: 0.9,
        melting_point: [ 235, 238 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
        cas_no: '53-39-4',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 3.5431000000000004,
        formula: 'C19H30O3',
        smiles: 'CC12COC(=O)CC1CCC1C2CCC2(C)C1CCC2(C)O'
    },
    {
        id: 'd2fa98fe-9f46-4b9b-adff-51dbe08c1f4e',
        class: 'ingredient',
        name: 'Turinabol',
        translations: {
            en: 'Turinabol',
            fr: 'Turinabol',
            es: 'Turinabol',
            de: 'Turinabol',
            it: 'Turinabol',
            nl: 'Turinabol',
            pt: 'Turinabol',
            ru: 'Туринабол',
            ja: 'トリナボル',
            zh: '图林博',
            ko: '투리나볼',
            ar: 'تورينابول',
            hi: 'ट्यूरिनाबोल',
            id: 'Turinabol',
            tr: 'Turinabol',
            pl: 'Turinabol',
            sv: 'Turinabol',
            da: 'Turinabol',
            no: 'Turinabol',
            cs: 'Turinabol',
            hu: 'Turinabol',
            vi: 'Turinabol'
        },
        pubchemid: null,
        self_id: 'turinabol',
        molecular_weight: 0,
        density: 1.2048192771084338,
        displacement: 0.83,
        melting_point: [ 225, 230 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 8.4,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "2446-23-3",
        smiles: "O=C1\\C=C/[C@]4(/C(=C1/Cl)CC[C@@H]3[C@@H]4CC[C@]2([C@H]3CC[C@@]2(O)C)C)C"
    },
    {
        id: '2d296c8d-7f1d-47a9-b973-148aeadfbca3',
        class: 'ingredient',
        name: 'Winstrol',
        cas_no: '10418-03-8',
        log_p: 3.6361999999999997,
        translations: {
            en: 'Winstrol',
            fr: 'Winstrol',
            es: 'Winstrol',
            de: 'Winstrol',
            it: 'Winstrol',
            nl: 'Winstrol',
            pt: 'Winstrol',
            ru: 'Винстрол',
            ja: 'ウィンストロール',
            zh: '康力龙',
            ko: '윈스트롤',
            ar: 'وينسترول',
            hi: 'विन्स्ट्रोल',
            id: 'Winstrol',
            tr: 'Winstrol',
            pl: 'Winstrol',
            sv: 'Winstrol',
            da: 'Winstrol',
            no: 'Winstrol',
            cs: 'Winstrol',
            hu: 'Winstrol',
            vi: 'Winstrol'
        },
        pubchemid: null,
        self_id: 'winstrol',
        molecular_weight: 328.4916,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 228, 242 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 1.95,
        image: null,
        mol2d: null,
        mol3d: null,
        formula: 'C21H32N2O',
        smiles: 'CC12Cc3c[nH]nc3CC1CCC1C2CCC2(C)C1CCC2(C)O'
    },
    {
        id: '4075e0a8-83c5-4638-b069-fca10c3a45cb',
        class: 'ingredient',
        name: 'Proviron',
        translations: {
            en: 'Proviron',
            fr: 'Proviron',
            es: 'Proviron',
            de: 'Proviron',
            it: 'Proviron',
            nl: 'Proviron',
            pt: 'Proviron',
            ru: 'Провирон',
            ja: 'プロビロン',
            zh: '普维雄',
            ko: '프로비론',
            ar: 'بروفيرون',
            hi: 'प्रोविरोन',
            id: 'Proviron',
            tr: 'Proviron',
            pl: 'Proviron',
            sv: 'Proviron',
            da: 'Proviron',
            no: 'Proviron',
            cs: 'Proviron',
            hu: 'Proviron',
            vi: 'Proviron'
        },
        pubchemid: null,
        self_id: 'proviron',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 206, 210 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 3,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "1424-00-6",
        smiles: "O=C4C[C@@H]3CC[C@@H]2[C@H](CC[C@]1(C)[C@@H](O)CC[C@H]12)[C@@]3(C)[C@@H](C)C4"
    },
    {
        id: '81743da0-5102-41ec-8168-4ecc518e7490',
        class: 'ingredient',
        name: 'Halotestin',
        translations: {
            en: 'Halotestin',
            fr: 'Halotestin',
            es: 'Halotestin',
            de: 'Halotestin',
            it: 'Halotestin',
            nl: 'Halotestin',
            pt: 'Halotestin',
            ru: 'Халотестин',
            ja: 'ハロテスチン',
            zh: '哈洛泰斯汀',
            ko: '할로테스틴',
            ar: 'هالوتستين',
            hi: 'हैलोटेस्टिन',
            id: 'Halotestin',
            tr: 'Halotestin',
            pl: 'Halotestin',
            sv: 'Halotestin',
            da: 'Halotestin',
            no: 'Halotestin',
            cs: 'Halotestin',
            hu: 'Halotestin',
            vi: 'Halotestin'
        },
        pubchemid: null,
        self_id: 'halotestin',
        molecular_weight: 336.4409,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 238, 242 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 39.8,
        cas_no: '76-43-7',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 3.3322,
        formula: 'C20H29FO3',
        smiles: 'CC1(O)CCC2C3CCC4=CC(=O)CCC4(C)C3(F)C(O)CC21C'
    },
    {
        id: 'd6e7104a-259b-4593-a2bd-9282fadaa4bc',
        class: 'ingredient',
        name: 'Methyltrienolone',
        translations: {
            en: 'methyltrienolone',
            fr: 'méthyltriénolone',
            es: 'metiltrienolona',
            de: 'Methyltrienolon',
            it: 'metiltrienolone',
            nl: 'methyltrienolon',
            pt: 'metiltrienolona',
            ru: 'метилтриенолон',
            ja: 'メチルトリエノロン',
            zh: '甲基三烯诺龙',
            ko: '메틸트리에놀론',
            ar: 'ميثيلترينولون',
            hi: 'मेथिलट्रिएनोलोन',
            id: 'metiltrienolon',
            tr: 'metiltrienolon',
            pl: 'metyltrienolon',
            sv: 'metyltrienolon',
            da: 'methyltrienolon',
            no: 'methyltrienolon',
            cs: 'methyltrienolon',
            hu: 'metiltrienolon',
            vi: 'methyltrienolone'
        },
        pubchemid: null,
        self_id: 'methyltrienolone',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [ 165, 170 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "965-93-5",
        smiles: "C[C@@]1(CC[C@@H]2[C@@]1(C=CC3=C4CCC(=O)C=C4CC[C@@H]23)C)O"
    },
    {
        id: '17c3ca3d-2223-4617-8069-29b7f095febd',
        class: 'ingredient',
        name: 'Methyl-1-Testosterone',
        translations: {
            en: 'methyl-1-testosterone',
            fr: 'méthyl-1-testostérone',
            es: 'metil-1-testosterona',
            de: 'Methyl-1-Testosteron',
            it: 'metil-1-testosterone',
            nl: 'methyl-1-testosteron',
            pt: 'metil-1-testosterona',
            ru: 'метил-1-тестостерон',
            ja: 'メチル-1-テストステロン',
            zh: '甲基-1-睾酮',
            ko: '메틸-1-테스토스테론',
            ar: 'ميثيل-1-تستوستيرون',
            hi: 'मेथिल-1-टेस्टोस्टेरोन',
            id: 'metil-1-testosteron',
            tr: 'metil-1-testosteron',
            pl: 'metyl-1-testosteron',
            sv: 'metyl-1-testosteron',
            da: 'methyl-1-testosteron',
            no: 'methyl-1-testosteron',
            cs: 'methyl-1-testosteron',
            hu: 'metil-1-tesztoszteron',
            vi: 'methyl-1-testosterone'
        },
        pubchemid: null,
        self_id: 'methyl,1,testosterone',
        molecular_weight: 0,
        density: 1.0869565217391304,
        displacement: 0.92,
        melting_point: [ 154, 155 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "65-04-3",
        smiles: "O=C4\\C=C/[C@]1([C@@H](CC[C@@H]2[C@@H]1CC[C@]3([C@H]2CC[C@@]3(O)C)C)C4)C"
    },
    {
        id: 'a76186d2-019d-432c-a73b-780beff2e3bb',
        class: 'ingredient',
        name: 'Superdrol',
        translations: {
            en: 'Superdrol',
            fr: 'Superdrol',
            es: 'Superdrol',
            de: 'Superdrol',
            it: 'Superdrol',
            nl: 'Superdrol',
            pt: 'Superdrol',
            ru: 'Супердрол',
            ja: 'スーパードロール',
            zh: '超级卓尔',
            ko: '슈퍼드롤',
            ar: 'سوبردرول',
            hi: 'सुपरड्रोल',
            id: 'Superdrol',
            tr: 'Superdrol',
            pl: 'Superdrol',
            sv: 'Superdrol',
            da: 'Superdrol',
            no: 'Superdrol',
            cs: 'Superdrol',
            hu: 'Superdrol',
            vi: 'Superdrol'
        },
        pubchemid: null,
        self_id: 'superdrol',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [ 148, 150 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 8.76,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "3381-88-2",
        smiles: "O=C2C[C@@H]1CC[C@@H]3[C@@H]([C@@]1(C)C[C@H]2C)CC[C@]4([C@H]3CC[C@@]4(O)C)C"
    },
    {
        id: 'ab86ff4e-2d7a-483c-9a2a-c950460646bf',
        class: 'ingredient',
        name: 'Methyl-DHT',
        translations: {
            en: 'methyl-DHT',
            fr: 'méthyl-DHT',
            es: 'metil-DHT',
            de: 'Methyl-DHT',
            it: 'metil-DHT',
            nl: 'methyl-DHT',
            pt: 'metil-DHT',
            ru: 'метил-ДГТ',
            ja: 'メチルDHT',
            zh: '甲基DHT',
            ko: '메틸-DHT',
            ar: 'ميثيل-DHT',
            hi: 'मेथिल-DHT',
            id: 'metil-DHT',
            tr: 'metil-DHT',
            pl: 'metyl-DHT',
            sv: 'metyl-DHT',
            da: 'methyl-DHT',
            no: 'methyl-DHT',
            cs: 'methyl-DHT',
            hu: 'metil-DHT',
            vi: 'methyl-DHT'
        },
        pubchemid: null,
        self_id: 'methyl,dht',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [ 185, 192 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: '521-11-9',
        smiles: "O=C2C[C@@H]1CC[C@@H]3[C@@H]([C@@]1(C)CC2)CC[C@]4([C@H]3CC[C@@]4(O)C)C"
    },
    {
        id: '2af4dc5f-c3f8-4121-a5fa-ceed8f184573',
        class: 'ingredient',
        name: 'Aromasin',
        translations: {
            en: 'Aromasin',
            fr: 'Aromasin',
            es: 'Aromasin',
            de: 'Aromasin',
            it: 'Aromasin',
            nl: 'Aromasin',
            pt: 'Aromasin',
            ru: 'Аромазин',
            ja: 'アロマシン',
            zh: '阿诺新',
            ko: '아로마신',
            ar: 'أروماسين',
            hi: 'अरोमासिन',
            id: 'Aromasin',
            tr: 'Aromasin',
            pl: 'Aromasin',
            sv: 'Aromasin',
            da: 'Aromasin',
            no: 'Aromasin',
            cs: 'Aromasin',
            hu: 'Aromasin',
            vi: 'Aromasin'
        },
        pubchemid: null,
        self_id: 'aromasin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 153, 157 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 3,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "107868-30-4",
        smiles: "O=C\\1\\C=C/[C@]3(C(=C/1)/C(=C)C[C@H]4[C@@H]2CCC(=O)[C@]2(CC[C@H]34)C)C"
    },
    {
        id: '10edc0ac-64ba-4a3c-b412-375ef56d3b60',
        class: 'ingredient',
        name: 'Arimidex',
        translations: {
            en: 'Arimidex',
            fr: 'Arimidex',
            es: 'Arimidex',
            de: 'Arimidex',
            it: 'Arimidex',
            nl: 'Arimidex',
            pt: 'Arimidex',
            ru: 'Аримидекс',
            ja: 'アリミデックス',
            zh: '阿里米德',
            ko: '아리미덱스',
            ar: 'أريميدكس',
            hi: 'अरिमिडेक्स',
            id: 'Arimidex',
            tr: 'Arimidex',
            pl: 'Arimidex',
            sv: 'Arimidex',
            da: 'Arimidex',
            no: 'Arimidex',
            cs: 'Arimidex',
            hu: 'Arimidex',
            vi: 'Arimidex'
        },
        pubchemid: null,
        self_id: 'arimidex',
        molecular_weight: 293.3663,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [ 81, 82 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 3.5,
        cas_no: '120511-73-1',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 2.9287599999999996,
        formula: 'C17H19N5',
        smiles: 'CC(C)(C#N)c1cc(Cn2cncn2)cc(C(C)(C)C#N)c1'
    },
    {
        id: 'a321091c-f508-4f4b-9bda-d84e8dbe18b1',
        class: 'ingredient',
        name: 'Letrozole',
        translations: {
            en: 'letrozole',
            fr: 'létrozole',
            es: 'letrozol',
            de: 'Letrozol',
            it: 'letrozolo',
            nl: 'letrozol',
            pt: 'letrozol',
            ru: 'летрозол',
            ja: 'レトロゾール',
            zh: '来曲唑',
            ko: '레트로졸',
            ar: 'ليتروزول',
            hi: 'लेट्रोज़ोल',
            id: 'letrozole',
            tr: 'letrozol',
            pl: 'letrozol',
            sv: 'letrozol',
            da: 'letrozol',
            no: 'letrozol',
            cs: 'letrozol',
            hu: 'letrozol',
            vi: 'letrozole'
        },
        pubchemid: null,
        self_id: 'letrozole',
        molecular_weight: 285.3027,
        density: 1.2195121951219512,
        displacement: 0.82,
        melting_point: [ 181, 186 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        cas_no: '112809-51-5',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 2.65916,
        formula: 'C17H11N5',
        smiles: 'N#Cc1ccc(C(c2ccc(C#N)cc2)n2cncn2)cc1'
    },
    {
        id: '0e68f0ea-c042-4aef-9ede-12a7daf6e6be',
        class: 'ingredient',
        name: 'Pramipexole',
        translations: {
            en: 'pramipexole',
            fr: 'pramipexole',
            es: 'pramipexol',
            de: 'Pramipexol',
            it: 'pramipexolo',
            nl: 'pramipexol',
            pt: 'pramipexol',
            ru: 'прамипексол',
            ja: 'プラミペキソール',
            zh: '普拉克索',
            ko: '프라미펙솔',
            ar: 'براميبيكسول',
            hi: 'प्रामिपेक्सोल',
            id: 'pramipexole',
            tr: 'pramipeksol',
            pl: 'pramipeksol',
            sv: 'pramipexol',
            da: 'pramipexol',
            no: 'pramipexol',
            cs: 'pramipexol',
            hu: 'pramipexol',
            vi: 'pramipexole'
        },
        pubchemid: null,
        self_id: 'pramipexole',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [ 118, 122 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        mol2d: null,
        mol3d: null,
        image: null,
        cas_no: "104632-26-0",
        smiles: "n1c2c(sc1N)C[C@@H](NCCC)CC2"
    },
    {
        id: '86cd731a-c5d7-4436-b89e-f4d42799f61d',
        class: 'ingredient',
        name: 'Tamoxifen',
        translations: {
            en: 'tamoxifen',
            fr: 'tamoxifène',
            es: 'tamoxifeno',
            de: 'Tamoxifen',
            it: 'tamoxifene',
            nl: 'tamoxifen',
            pt: 'tamoxifeno',
            ru: 'тамоксифен',
            ja: 'タモキシフェン',
            zh: '他莫昔芬',
            ko: '타목시펜',
            ar: 'تاموكسيفين',
            hi: 'टैमोक्सीफेन',
            id: 'tamoxifen',
            tr: 'tamoksifen',
            pl: 'tamoksyfen',
            sv: 'tamoxifen',
            da: 'tamoxifen',
            no: 'tamoxifen',
            cs: 'tamoxifen',
            hu: 'tamoxifen',
            vi: 'tamoxifen'
        },
        pubchemid: null,
        self_id: 'tamoxifen',
        molecular_weight: 371.5146,
        density: 1,
        displacement: 1,
        melting_point: [ 143, 146 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        cas_no: '10540-29-1',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 5.9961,
        formula: 'C26H29NO',
        smiles: 'CCC(=C(c1ccccc1)c1ccc(OCCN(C)C)cc1)c1ccccc1'
    },
    {
        id: '4ae9e796-2887-42f7-aa00-b5586b6f940c',
        class: 'ingredient',
        name: 'Clomiphene',
        translations: {
            en: 'clomiphene',
            fr: 'clomifène',
            es: 'clomifeno',
            de: 'Clomifen',
            it: 'clomifene',
            nl: 'clomifeen',
            pt: 'clomifeno',
            ru: 'кломифен',
            ja: 'クロミフェン',
            zh: '克罗米芬',
            ko: '클로미펜',
            ar: 'كلوميفين',
            hi: 'क्लोमीफीन',
            id: 'clomiphene',
            tr: 'klomifen',
            pl: 'klomifen',
            sv: 'klomifen',
            da: 'clomifen',
            no: 'klomifen',
            cs: 'klomifen',
            hu: 'klomifén',
            vi: 'clomiphene'
        },
        pubchemid: null,
        self_id: 'clomiphene',
        molecular_weight: 405.96,
        density: 1,
        displacement: 1,
        melting_point: [ 116, 118 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
        cas_no: '911-45-5',
        image: null,
        mol2d: null,
        mol3d: null,
        log_p: 6.5626,
        formula: 'C26H28ClNO',
        smiles: 'CCN(CC)CCOc1ccc(C(=C(Cl)c2ccccc2)c2ccccc2)cc1'
    },
    {
        id: '039fd136-3f99-4fac-bed2-d18f7b8f55f5',
        class: 'ingredient',
        name: 'YK11 (experimental)',
        translations: {
            en: 'YK11',
            fr: 'YK11',
            es: 'YK11',
            de: 'YK11',
            it: 'YK11',
            nl: 'YK11',
            pt: 'YK11',
            ru: 'YK-11',
            ja: 'ワイケー11',
            zh: 'YK11',
            ko: '와이케이11',
            ar: 'واي كيه 11',
            hi: 'वाईके11',
            id: 'YK11',
            tr: 'YK11',
            pl: 'YK11',
            sv: 'YK11',
            da: 'YK11',
            no: 'YK11',
            cs: 'YK11',
            hu: 'YK11',
            vi: 'YK11'
        },
        pubchemid: null,
        cas_no: '1370003-76-1',
        self_id: 'yk11',
        molecular_weight: 430.53,
        density: 1.22,
        displacement: 0.82,
        melting_point: [ 564.4 ],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "O=C(OC)/C=C1OC(OC)(C)O[C@@]2/1CC[C@@]3([H])[C@]4([H])CCC5=CC(CC[C@]5([H])[C@@]4([H])CC[C@@]32C)=O"
    },
    {
        id: 'crypto.randomUUID()',
        class: 'ingredient',
        name: 'SLU-PP-332 (experimental)',
        translations: {
            en: 'SLU-PP-332',
            fr: 'SLU-PP-332',
            es: 'SLU-PP-332',
            de: 'SLU-PP-332',
            it: 'SLU-PP-332',
            nl: 'SLU-PP-332',
            pt: 'SLU-PP-332',
            ru: 'SLU-PP-332',
            ja: 'SLU-PP-332',
            zh: 'SLU-PP-332',
            ko: 'SLU-PP-332',
            ar: 'SLU-PP-332',
            hi: 'SLU-PP-332',
            id: 'SLU-PP-332',
            tr: 'SLU-PP-332',
            pl: 'SLU-PP-332',
            sv: 'SLU-PP-332',
            da: 'SLU-PP-332',
            no: 'SLU-PP-332',
            cs: 'SLU-PP-332',
            hu: 'SLU-PP-332',
            vi: 'SLU-PP-332'
        },
        pubchemid: 5338394,
        cas_no: '303760-60-3',
        self_id: 'slu-pp-332',
        molecular_weight: 290.32,
        density: 1.2,
        displacement: 0.83,
        melting_point: 500,
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: 'mg_per_ml',
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
        mol2d: null,
        mol3d: null,
        image: null,
        smiles: "C(NN=CC1=CC=C2C(=C1)C=CC=C2)(=O)C1=CC=C(O)C=C1"
    }
]

var solubility = [
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Long Length Esters',
        self_id: 'long_length_esters',
        low_solvent_range: [200, 300], // 0-10%
        medium_solvent_range: [300, 400], // 20-30%
        high_solvent_range: [400, 500], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_decanoate',
            'testosterone_undecanoate',
            'dihydroboldenone_undecylenate',
            'nandrolone_decanoate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Medium Length Esters',
        self_id: 'medium_length_esters',
        low_solvent_range: [100, 150], // 0-10%
        medium_solvent_range: [150, 250], // 20-30%
        high_solvent_range: [250, 350], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_cypionate',
            'testosterone_enanthate',
            'testosterone_phenylpropionate',
            'nandrolone_phenylpropionate',
            'dihydroboldenone_cypionate',
            'drostanolone_enanthate',
            'methenolone_enanthate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Short Length Esters',
        self_id: 'short_length_esters',
        low_solvent_range: [0, 50], // 0-10%
        medium_solvent_range: [50, 100], // 20-30%
        high_solvent_range: [100, 150], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_acetate',
            'testosterone_propionate',
            'trenbolone_acetate',
            'methenolone_acetate',
        ]
    }
]