var compounds = [
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "benzyl benzoate",
        pubchemid: null,
        self_id: "benzyl_benzoate",
        molecular_weight: 212.24, // g/mol
        density: 1.118, // g/mL @ 20c
        viscosityArray: [8.292], // cP
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "v_v_percent"
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "benzyl alcohol",
        pubchemid: null,
        self_id: "benzyl_alcohol",
        molecular_weight: 108.14, // g/mol
        density: 1.044, // g/mL (g/cm3) @ 20c
        viscosityArray: [5.474], // cP
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "v_v_percent"
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "ethyl oleate",
        pubchemid: 5363269,
        self_id: "ethyl_oleate",
        molecular_weight: 310.5, // g/mol
        density: 0.87, // 0.868-0.873g/cm^3
        viscosityArray: [5.15], // cP
        viscosityTempArray: [25],
        evaporation_point: 250.15,
        boiling_point: 217,
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "q.s."
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "castor oil",
        pubchemid: null,
        self_id: "castor",
        molecular_weight: null,
        density: 0.96, // 0.957 -0.9656 g/mL
        viscosityArray: [580, 283, 36],
        viscosityTempArray: [27, 37, 79.4],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "q.s."
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "MCT",
        pubchemid: null,
        self_id: "MCT",
        molecular_weight: null,
        density: 0.942,
        viscosityArray: [23, 12],
        viscosityTempArray: [25, 37],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "q.s."
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "cottonseed oil",
        pubchemid: null,
        self_id: "cottonseed",
        molecular_weight: null,
        density: 0.92, //0.918–0.926
        viscosityArray: [70],
        viscosityTempArray: [20],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: "q.s."
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone base',
        pubchemid: null,
        self_id: 'testosterone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone acetate',
        pubchemid: null,
        self_id: 'testosterone_acetate',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [140, 144],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone propionate',
        pubchemid: null,
        self_id: 'testosterone_propionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone phenylpropionate',
        pubchemid: null,
        self_id: 'testosterone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        boiling_point: [115, 116],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone cypionate',
        pubchemid: null,
        self_id: 'testosterone_cypionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [98, 102],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone enanthate',
        pubchemid: null,
        self_id: 'testosterone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [32, 36],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone decanoate',
        pubchemid: null,
        self_id: 'testosterone_decanoate',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [47, 49],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone undecanoate',
        pubchemid: null,
        self_id: 'testosterone_undecanoate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        boiling_point: [59, 61],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone base',
        pubchemid: null,
        self_id: 'trenbolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [168, 172],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone acetate',
        pubchemid: null,
        self_id: 'trenbolone_acetate',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [94, 97],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone cyclohexylmethylcarbonate',
        pubchemid: null,
        self_id: 'trenbolone_cyclohexylmethylcarbonate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [183, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone enanthate',
        pubchemid: null,
        self_id: 'trenbolone_enanthate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [72, 78],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Drostanolone propionate',
        pubchemid: null,
        self_id: 'drostanolone_propionate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [125, 127],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Drostanolone enanthate',
        pubchemid: null,
        self_id: 'drostanolone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [53, 56],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methenolone acetate',
        pubchemid: null,
        self_id: 'methenolone_acetate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [141, 143],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methenolone enanthate',
        pubchemid: null,
        self_id: 'methenolone_enanthate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        boiling_point: [66, 71],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone base',
        pubchemid: null,
        self_id: 'nandrolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [120, 125],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone phenylpropionate',
        pubchemid: null,
        self_id: 'nandrolone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        boiling_point: [85, 87],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone decanoate',
        pubchemid: null,
        self_id: 'nandrolone_decanoate',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [30, 35],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Boldenone base',
        pubchemid: null,
        self_id: 'boldenone_base',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [163, 166],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Boldenone undecylenate',
        pubchemid: null,
        self_id: 'boldenone_undecylenate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        boiling_point: [0],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Dihydroboldenone cypionate',
        pubchemid: null,
        self_id: 'dihydroboldenone_cypionate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        boiling_point: [192, 196],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Dianabol',
        pubchemid: null,
        self_id: 'dianabol',
        molecular_weight: 0,
        density: 1.075268817204301,
        displacement: 0.93,
        boiling_point: [164, 167],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Anadrol',
        pubchemid: null,
        self_id: 'anadrol',
        molecular_weight: 0,
        density: 1.1627906976744187,
        displacement: 0.86,
        boiling_point: [177, 180],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Anavar',
        pubchemid: null,
        self_id: 'anavar',
        molecular_weight: 0,
        density: 1.1111111111111112,
        displacement: 0.9,
        boiling_point: [235, 238],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Turinabol',
        pubchemid: null,
        self_id: 'turinabol',
        molecular_weight: 0,
        density: 1.2048192771084338,
        displacement: 0.83,
        boiling_point: [225, 230],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Winstrol',
        pubchemid: null,
        self_id: 'winstrol',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [228, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Proviron',
        pubchemid: null,
        self_id: 'proviron',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [206, 210],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Halotestin',
        pubchemid: null,
        self_id: 'halotestin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [238, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyltrienolone',
        pubchemid: null,
        self_id: 'methyltrienolone',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [165, 170],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyl,1,Testosterone',
        pubchemid: null,
        self_id: 'methyl,1,testosterone',
        molecular_weight: 0,
        density: 1.0869565217391304,
        displacement: 0.92,
        boiling_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Superdrol',
        pubchemid: null,
        self_id: 'superdrol',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [148, 150],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyl,DHT',
        pubchemid: null,
        self_id: 'methyl,dht',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [185, 192],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Aromasin',
        pubchemid: null,
        self_id: 'aromasin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [153, 157],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Arimidex',
        pubchemid: null,
        self_id: 'arimidex',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [81, 82],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Letrozole',
        pubchemid: null,
        self_id: 'letrozole',
        molecular_weight: 0,
        density: 1.2195121951219512,
        displacement: 0.82,
        boiling_point: [181, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Pramipexole',
        pubchemid: null,
        self_id: 'pramipexole',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Tamoxifen',
        pubchemid: null,
        self_id: 'tamoxifen',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        boiling_point: [143, 146],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Clomiphene',
        pubchemid: null,
        self_id: 'clomiphene',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        boiling_point: [116, 118],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone base',
        pubchemid: null,
        self_id: 'testosterone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone acetate',
        pubchemid: null,
        self_id: 'testosterone_acetate',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [140, 144],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone propionate',
        pubchemid: null,
        self_id: 'testosterone_propionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone phenylpropionate',
        pubchemid: null,
        self_id: 'testosterone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        boiling_point: [115, 116],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone cypionate',
        pubchemid: null,
        self_id: 'testosterone_cypionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [98, 102],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone enanthate',
        pubchemid: null,
        self_id: 'testosterone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [32, 36],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone decanoate',
        pubchemid: null,
        self_id: 'testosterone_decanoate',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [47, 49],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Testosterone undecanoate',
        pubchemid: null,
        self_id: 'testosterone_undecanoate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        boiling_point: [59, 61],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone base',
        pubchemid: null,
        self_id: 'trenbolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [168, 172],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone acetate',
        pubchemid: null,
        self_id: 'trenbolone_acetate',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [94, 97],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone cyclohexylmethylcarbonate',
        pubchemid: null,
        self_id: 'trenbolone_cyclohexylmethylcarbonate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [183, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Trenbolone enanthate',
        pubchemid: null,
        self_id: 'trenbolone_enanthate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [72, 78],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Drostanolone propionate',
        pubchemid: null,
        self_id: 'drostanolone_propionate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [125, 127],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Drostanolone enanthate',
        pubchemid: null,
        self_id: 'drostanolone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [53, 56],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methenolone acetate',
        pubchemid: null,
        self_id: 'methenolone_acetate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [141, 143],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methenolone enanthate',
        pubchemid: null,
        self_id: 'methenolone_enanthate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        boiling_point: [66, 71],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone base',
        pubchemid: null,
        self_id: 'nandrolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        boiling_point: [120, 125],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone phenylpropionate',
        pubchemid: null,
        self_id: 'nandrolone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        boiling_point: [85, 87],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Nandrolone decanoate',
        pubchemid: null,
        self_id: 'nandrolone_decanoate',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [30, 35],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Boldenone base',
        pubchemid: null,
        self_id: 'boldenone_base',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [163, 166],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Boldenone undecylenate',
        pubchemid: null,
        self_id: 'boldenone_undecylenate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        boiling_point: [0],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Dihydroboldenone cypionate',
        pubchemid: null,
        self_id: 'dihydroboldenone_cypionate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        boiling_point: [192, 196],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Dianabol',
        pubchemid: null,
        self_id: 'dianabol',
        molecular_weight: 0,
        density: 1.075268817204301,
        displacement: 0.93,
        boiling_point: [164, 167],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Anadrol',
        pubchemid: null,
        self_id: 'anadrol',
        molecular_weight: 0,
        density: 1.1627906976744187,
        displacement: 0.86,
        boiling_point: [177, 180],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Anavar',
        pubchemid: null,
        self_id: 'anavar',
        molecular_weight: 0,
        density: 1.1111111111111112,
        displacement: 0.9,
        boiling_point: [235, 238],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Turinabol',
        pubchemid: null,
        self_id: 'turinabol',
        molecular_weight: 0,
        density: 1.2048192771084338,
        displacement: 0.83,
        boiling_point: [225, 230],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Winstrol',
        pubchemid: null,
        self_id: 'winstrol',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [228, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Proviron',
        pubchemid: null,
        self_id: 'proviron',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [206, 210],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Halotestin',
        pubchemid: null,
        self_id: 'halotestin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [238, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyltrienolone',
        pubchemid: null,
        self_id: 'methyltrienolone',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [165, 170],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyl,1,Testosterone',
        pubchemid: null,
        self_id: 'methyl,1,testosterone',
        molecular_weight: 0,
        density: 1.0869565217391304,
        displacement: 0.92,
        boiling_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Superdrol',
        pubchemid: null,
        self_id: 'superdrol',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        boiling_point: [148, 150],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Methyl,DHT',
        pubchemid: null,
        self_id: 'methyl,dht',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        boiling_point: [185, 192],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Aromasin',
        pubchemid: null,
        self_id: 'aromasin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [153, 157],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Arimidex',
        pubchemid: null,
        self_id: 'arimidex',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        boiling_point: [81, 82],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Letrozole',
        pubchemid: null,
        self_id: 'letrozole',
        molecular_weight: 0,
        density: 1.2195121951219512,
        displacement: 0.82,
        boiling_point: [181, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Pramipexole',
        pubchemid: null,
        self_id: 'pramipexole',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        boiling_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Tamoxifen',
        pubchemid: null,
        self_id: 'tamoxifen',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        boiling_point: [143, 146],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: 'Clomiphene',
        pubchemid: null,
        self_id: 'clomiphene',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        boiling_point: [116, 118],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        basis: 'mg_per_ml'
    }
]


var solubility = [
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Long Length Esters',
        self_id: 'long_length_esters',
        low_solvent_range: [200, 300], // 0-10%
        medium_solvent_range: [300, 400], // 20-30%
        high_solvent_range: [400, 500], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_decanoate',
            'testosterone_undecanoate',
            'dihydroboldenone_undecylenate',
            'nandrolone_decanoate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Medium Length Esters',
        self_id: 'medium_length_esters',
        low_solvent_range: [100, 150], // 0-10%
        medium_solvent_range: [150, 250], // 20-30%
        high_solvent_range: [250, 350], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_cypionate',
            'testosterone_enanthate',
            'testosterone_phenylpropionate',
            'nandrolone_phenylpropionate',
            'dihydroboldenone_cypionate',
            'drostanolone_enanthate',
            'methenolone_enanthate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Short Length Esters',
        self_id: 'short_length_esters',
        low_solvent_range: [0, 50], // 0-10%
        medium_solvent_range: [50, 100], // 20-30%
        high_solvent_range: [100, 150], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_acetate',
            'testosterone_propionate',
            'trenbolone_acetate',
            'methenolone_acetate',
        ]
    }
]