var compounds = [
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "benzyl benzoate",
        translations: {
            en: "benzyl benzoate",
            fr: "benzoate de benzyle",
            es: "benzoato de bencilo",
            de: "Benzylbenzoat",
            it: "benzoato di benzile",
            nl: "benzylbenzoaat",
            pt: "benzoato de benzilo",
            ru: "бензилбензоат",
            ja: "安息香酸ベンジル",
            zh: "苯甲酸苄酯",
            ko: "벤질 벤조에이트",
            ar: "بنزيل بنزوات",
            hi: "बेंजिल बेंजोएट",
            id: "benzil benzoat",
            tr: "benzil benzoat",
            pl: "benzoesan benzylu",
            sv: "bensylbensoat",
            da: "benzylbenzoat",
            no: "benzylbenzoat",
            cs: "benzyl-benzoát",
            hu: "benzil-benzoát",
            vi: "benzyl benzoate"
        },
        pubchemid: null,
        self_id: "benzyl_benzoate",
        molecular_weight: 212.24, // g/mol
        density: 1.118, // g/mL @ 20c
        viscosityArray: [8.292], // cP
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 2,
        mg_per_ml: 0,
        purity: 100,
        basis: "v_v_percent",
        input: 0,
        qsMode: false,
        pricePerUnit: 198/1000,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "benzyl alcohol",
        translations: {
            en: "benzyl alcohol",
            fr: "alcool benzylique",
            es: "alcohol bencílico",
            de: "Benzylalkohol",
            it: "alcol benzilico",
            nl: "benzylalcohol",
            pt: "álcool benzílico",
            ru: "бензиловый спирт",
            ja: "ベンジルアルコール",
            zh: "苯甲醇",
            ko: "벤질 알코올",
            ar: "كحول بنزيل",
            hi: "बेंजिल अल्कोहल",
            id: "alkohol benzil",
            tr: "benzil alkol",
            pl: "alkohol benzylowy",
            sv: "bensylalkohol",
            da: "benzylalkohol",
            no: "benzylalkohol",
            cs: "benzylalkohol",
            hu: "benzil-alkohol",
            vi: "benzyl alcohol"
        },
        pubchemid: null,
        self_id: "benzyl_alcohol",
        molecular_weight: 108.14, // g/mol
        density: 1.044, // g/mL (g/cm3) @ 20c
        viscosityArray: [5.474], // cP
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 20,
        mg_per_ml: 0,
        purity: 100,
        basis: "v_v_percent",
        input: 0,
        qsMode: false,
        pricePerUnit: 110/1000,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "ethanol",
        translations: {
            en: "ethanol",
            fr: "éthanol",
            es: "etanol",
            de: "Ethanol",
            it: "etanolo",
            nl: "ethanol",
            pt: "etanol",
            ru: "этанол",
            ja: "エタノール",
            zh: "乙醇",
            ko: "에탄올",
            ar: "إيثانول",
            hi: "एथेनॉल",
            id: "etanol",
            tr: "etanol",
            pl: "etanol",
            sv: "etanol",
            da: "ethanol",
            no: "etanol",
            cs: "ethanol",
            hu: "etanol",
            vi: "ethanol"
        },
        pubchemid: 702,
        self_id: "ethanol",
        molecular_weight: 46.07, // g/mol
        density: 0.785, // g/mL (g/cm3) @ 25c
        viscosityArray: [1.04], // cP
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 20,
        mg_per_ml: 0,
        purity: 100,
        basis: "v_v_percent",
        input: 0,
        qsMode: false,
        pricePerUnit: 265/1000,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "Sterile Water for Injection",
        translations: {
            en: "Sterile Water for Injection",
            fr: "Eau stérile pour injection",
            es: "Agua estéril para inyección",
            de: "Steriles Wasser zur Injektion",
            it: "Acqua sterile per iniezione",
            nl: "Steriel water voor injectie",
            pt: "Água estéril para injeção",
            ru: "Стерильная вода для инъекций",
            ja: "注射用水",
            zh: "注射用水",
            ko: "주사용 멸균수",
            ar: "ماء معقم للحقن",
            hi: "इंजेक्शन के लिए बाँझ पानी",
            id: "Air Steril untuk Injeksi",
            tr: "Enjeksiyonluk Steril Su",
            pl: "Woda do wstrzykiwań jałowa",
            sv: "Sterilt vatten för injektion",
            da: "Sterilt vand til injektion",
            no: "Sterilt vann til injeksjon",
            cs: "Sterilní voda pro injekci",
            hu: "Steril injekcióhoz való víz",
            vi: "Nước vô trùng để tiêm"
        },
        pubchemid: 962,
        self_id: "sterile-water-for-injection",
        molecular_weight: 18.02,       // g/mol
        density: 1.0,                  // g/mL @ ~25°C
        viscosityArray: [0.89],        // cP at 25°C
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 0,                // Usually used as QS (quantity sufficient)
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.1,             // Example - adjust to your actual cost
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "ethyl oleate",
        translations: {
            en: "ethyl oleate",
            fr: "oléate d'éthyle",
            es: "oleato de etilo",
            de: "Ethyloleat",
            it: "oleato di etile",
            nl: "ethyloleaat",
            pt: "oleato de etila",
            ru: "этилолеат",
            ja: "オレイン酸エチル",
            zh: "油酸乙酯",
            ko: "에틸 올리에이트",
            ar: "أولييت الإيثيل",
            hi: "एथिल ओलिएट",
            id: "etil oleat",
            tr: "etil oleat",
            pl: "oleinian etylu",
            sv: "etyloleat",
            da: "ethyloleat",
            no: "etyloleat",
            cs: "ethyloleát",
            hu: "etil-oleát",
            vi: "ethyl oleate"
        },
        pubchemid: 5363269,
        self_id: "ethyl_oleate",
        molecular_weight: 310.5, // g/mol
        density: 0.87, // 0.868-0.873g/cm^3
        viscosityArray: [5.15], // cP
        viscosityTempArray: [25],
        evaporation_point: 250.15,
        melting_point: 217,
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "castor oil",
        translations: {
            en: "castor oil",
            fr: "huile de ricin",
            es: "aceite de ricino",
            de: "Rizinusöl",
            it: "olio di ricino",
            nl: "ricinusolie",
            pt: "óleo de rícino",
            ru: "касторовое масло",
            ja: "ヒマシ油",
            zh: "蓖麻油",
            ko: "피마자유",
            ar: "زيت الخروع",
            hi: "अरंडी का तेल",
            id: "minyak jarak",
            tr: "hint yağı",
            pl: "olej rycynowy",
            sv: "ricinolja",
            da: "ricinusolie",
            no: "ricinusolje",
            cs: "ricinový olej",
            hu: "ricinusolaj",
            vi: "dầu thầu dầu"
        },
        pubchemid: null,
        self_id: "castor",
        molecular_weight: null,
        density: 0.96, // 0.957 -0.9656 g/mL
        viscosityArray: [580, 283, 36],
        viscosityTempArray: [27, 37, 79.4],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 90/1000,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "MCT oil",
        translations: {
            en: "MCT oil",
            fr: "huile TCM",
            es: "aceite MCT",
            de: "MCT-Öl",
            it: "olio MCT",
            nl: "MCT-olie",
            pt: "óleo MCT",
            ru: "МСТ масло",
            ja: "MCTオイル",
            zh: "MCT油",
            ko: "MCT 오일",
            ar: "زيت MCT",
            hi: "एमसीटी तेल",
            id: "minyak MCT",
            tr: "MCT yağı",
            pl: "olej MCT",
            sv: "MCT-olja",
            da: "MCT-olie",
            no: "MCT-olje",
            cs: "MCT olej",
            hu: "MCT olaj",
            vi: "dầu MCT"
        },
        pubchemid: null,
        self_id: "MCT",
        molecular_weight: null,
        density: 0.942,
        viscosityArray: [23, 12],
        viscosityTempArray: [25, 37],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "cottonseed oil",
        translations: {
            en: "cottonseed oil",
            fr: "huile de coton",
            es: "aceite de semilla de algodón",
            de: "Baumwollsamenöl",
            it: "olio di semi di cotone",
            nl: "katoenzaadolie",
            pt: "óleo de semente de algodão",
            ru: "хлопковое масло",
            ja: "綿実油",
            zh: "棉籽油",
            ko: "면실유",
            ar: "زيت بذور القطن",
            hi: "कपास बीज तेल",
            id: "minyak biji kapas",
            tr: "pamuk tohumu yağı",
            pl: "olej z nasion bawełny",
            sv: "bomullsfröolja",
            da: "bomuldsfrøolie",
            no: "bomullsfrøolje",
            cs: "bavlníkový olej",
            hu: "gyapotmagolaj",
            vi: "dầu hạt bông"
        },
        pubchemid: null,
        self_id: "cottonseed",
        molecular_weight: null,
        density: 0.92, //0.918–0.926
        viscosityArray: [70],
        viscosityTempArray: [20],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "grapeseed oil",
        translations: {
            en: "grapeseed oil",
            fr: "huile de pépins de raisin",
            es: "aceite de semilla de uva",
            de: "Traubenkernöl",
            it: "olio di semi d'uva",
            nl: "druivenpitolie",
            pt: "óleo de semente de uva",
            ru: "масло виноградных косточек",
            ja: "グレープシードオイル",
            zh: "葡萄籽油",
            ko: "포도씨유",
            ar: "زيت بذور العنب",
            hi: "अंगूर बीज तेल",
            id: "minyak biji anggur",
            tr: "üzüm çekirdeği yağı",
            pl: "olej z pestek winogron",
            sv: "druvkärneolja",
            da: "vindruekerneolie",
            no: "druekjerneolje",
            cs: "hroznový olej",
            hu: "szőlőmagolaj",
            vi: "dầu hạt nho"
        },
        cas_no: '8024-22-4',
        pubchemid: null,
        self_id: "grapeseed",
        molecular_weight: null,
        density: 0.92, //0.918–0.926
        viscosityArray: [87.8],
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        // Source: https://doi.org/10.1063/5.0052635
        id: crypto.randomUUID(),
        class: "excipient",
        name: "arachis oil",
        translations: {
            en: "arachis oil",
            fr: "huile d'arachide",
            es: "aceite de cacahuete",
            de: "Erdnussöl",
            it: "olio di arachidi",
            nl: "arachideolie",
            pt: "óleo de amendoim",
            ru: "арахисовое масло",
            ja: "落花生油",
            zh: "花生油",
            ko: "땅콩기름",
            ar: "زيت الفول السوداني",
            hi: "मूंगफली का तेल",
            id: "minyak kacang tanah",
            tr: "yer fıstığı yağı",
            pl: "olej arachidowy",
            sv: "jordnötsolja",
            da: "jordnøddeolie",
            no: "peanøttolje",
            cs: "arašídový olej",
            hu: "földimogyoró-olaj",
            vi: "dầu đậu phộng"
        },
        cas_no: '8002-03-7',
        pubchemid: null,
        self_id: "arachis",
        molecular_weight: null,
        density: 0.9372, //0.918–0.926
        viscosityArray: [35.2], // TODO: find 25c viscosity
        viscosityTempArray: [37],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "sesame oil",
        translations: {
            en: "sesame oil",
            fr: "huile de sésame",
            es: "aceite de sésamo",
            de: "Sesamöl",
            it: "olio di sesamo",
            nl: "sesamolie",
            pt: "óleo de gergelim",
            ru: "кунжутное масло",
            ja: "ごま油",
            zh: "芝麻油",
            ko: "참기름",
            ar: "زيت السمسم",
            hi: "तिल का तेल",
            id: "minyak wijen",
            tr: "susam yağı",
            pl: "olej sezamowy",
            sv: "sesamolja",
            da: "sesamolie",
            no: "sesamolje",
            cs: "sezamový olej",
            hu: "szezámolaj",
            vi: "dầu mè"
        },
        cas_no: '8008-74-0',
        pubchemid: null,
        self_id: "sesame",
        molecular_weight: null,
        density: 0.92, //0.918–0.926
        viscosityArray: [45], // TODO: find 25c viscosity
        viscosityTempArray: [25],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: "excipient",
        name: "corn oil",
        translations: {
            en: "corn oil",
            fr: "huile de maïs",
            es: "aceite de maíz",
            de: "Maisöl",
            it: "olio di mais",
            nl: "maïsolie",
            pt: "óleo de milho",
            ru: "кукурузное масло",
            ja: "コーン油",
            zh: "玉米油",
            ko: "옥수수유",
            ar: "زيت الذرة",
            hi: "मकई का तेल",
            id: "minyak jagung",
            tr: "mısır yağı",
            pl: "olej kukurydziany",
            sv: "majsolja",
            da: "majsolie",
            no: "maisolje",
            cs: "kukuřičný olej",
            hu: "kukoricaolaj",
            vi: "dầu ngô"
        },
        cas_no: '8024-22-4',
        pubchemid: null,
        self_id: "corn",
        molecular_weight: null,
        density: 0.92, //0.918–0.926
        viscosityArray: [28, 30],
        viscosityTempArray: [57, 60],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "q.s.",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        cas_no: '53-43-0',
        name: "DHEA base",
        translations: {
            en: "DHEA base",
            fr: "prastérone",
            es: "prasterona",
            de: "Prasteron",
            it: "prasterone",
            nl: "prasteron",
            pt: "prasterona",
            ru: "прастерон",
            ja: "プラステロン",
            zh: "普拉睾酮",
            ko: "프라스테론",
            ar: "براستيرون",
            hi: "प्रास्टेरोन",
            id: "prasteron",
            tr: "prasteron",
            pl: "prasteron",
            sv: "prasteron",
            da: "prasteron",
            no: "prasteron",
            cs: "prasteron",
            hu: "praszteron",
            vi: "prasterone"
        },
        pubchemid: null,
        self_id: 'dhea_base',
        molecular_weight: 288.43,
        density: 1.05,
        displacement: 0.90,
        melting_point: [146, 151],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.2,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone base",
        translations: {
            en: "testosterone base",
            fr: "testostérone base",
            es: "testosterona base",
            de: "Testosteron-Base",
            it: "testosterone base",
            nl: "testosteronbasis",
            pt: "testosterona base",
            ru: "тестостероновая основа",
            ja: "テストステロンベース",
            zh: "基础睾酮",
            ko: "테스토스테론 베이스",
            ar: "التستوستيرون الأساسي",
            hi: "टेस्टोस्टेरोन बेस",
            id: "basis testosteron",
            tr: "testosteron bazı",
            pl: "baza testosteronu",
            sv: "testosteronbas",
            da: "testosteron-base",
            no: "testosteron-base",
            cs: "testosteron báze",
            hu: "tesztoszteron bázis",
            vi: "testosterone nền"
        },
        pubchemid: null,
        self_id: 'testosterone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.75,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone acetate",
        translations: {
            en: "testosterone acetate",
            fr: "acétate de testostérone",
            es: "acetato de testosterona",
            de: "Testosteronacetat",
            it: "acetato di testosterone",
            nl: "testosteronacetaat",
            pt: "acetato de testosterona",
            ru: "ацетат тестостерона",
            ja: "テストステロン酢酸エステル",
            zh: "醋酸睾酮",
            ko: "테스토스테론 아세테이트",
            ar: "أسيتات التستوستيرون",
            hi: "टेस्टोस्टेरोन एसीटेट",
            id: "testosteron asetat",
            tr: "testosteron asetat",
            pl: "octan testosteronu",
            sv: "testosteronacetat",
            da: "testosteronacetat",
            no: "testosteronacetat",
            cs: "testosteron acetát",
            hu: "tesztoszteron-acetát",
            vi: "testosterone acetate"
        },
        pubchemid: null,
        self_id: 'testosterone_acetate',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [140, 144],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
    }, {
        // source: https://www.chemicalbook.com/ChemicalProductProperty_US_CB9752601.aspx
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone isocaproate",
        translations: {
            en: "testosterone isocaproate",
            fr: "isocaproate de testostérone",
            es: "isocaproato de testosterona",
            de: "Testosteronisocaproat",
            it: "isocaproato di testosterone",
            nl: "testosteronisocaproaat",
            pt: "isocaproato de testosterona",
            ru: "изокапроат тестостерона",
            ja: "テストステロンイソカプロン酸エステル",
            zh: "异己酸睾酮",
            ko: "테스토스테론 이소카프로에이트",
            ar: "إيزوكابروات التستوستيرون",
            hi: "टेस्टोस्टेरोन आइसोकैप्रोएट",
            id: "testosteron isokaproat",
            tr: "testosteron izokaproat",
            pl: "izokapronian testosteronu",
            sv: "testosteronisokaproat",
            da: "testosteronisokaproat",
            no: "testosteronisokaproat",
            cs: "testosteron isokaproát",
            hu: "tesztoszteron-izokaproát",
            vi: "testosterone isocaproate"
        },
        cas_no: '15262-86-9',
        pubchemid: null,
        self_id: 'testosterone_isocaproate',
        molecular_weight: 386.57,
        density: 1.07,
        displacement: 0.89,
        melting_point: [79,81],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone propionate",
        translations: {
            en: "testosterone propionate",
            fr: "propionate de testostérone",
            es: "propionato de testosterona",
            de: "Testosteronpropionat",
            it: "propionato di testosterone",
            nl: "testosteronpropionaat",
            pt: "propionato de testosterona",
            ru: "пропионат тестостерона",
            ja: "テストステロンプロピオン酸エステル",
            zh: "丙酸睾酮",
            ko: "테스토스테론 프로피오네이트",
            ar: "بروبيونات التستوستيرون",
            hi: "टेस्टोस्टेरोन प्रोपियोनेट",
            id: "testosteron propionat",
            tr: "testosteron propiyonat",
            pl: "propionian testosteronu",
            sv: "testosteronpropionat",
            da: "testosteronpropionat",
            no: "testosteronpropionat",
            cs: "testosteron propionát",
            hu: "tesztoszteron-propionát",
            vi: "testosterone propionate"
        },
        pubchemid: null,
        self_id: 'testosterone_propionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.67,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone phenylpropionate",
        translations: {
            en: "testosterone phenylpropionate",
            fr: "phénylpropionate de testostérone",
            es: "fenilpropionato de testosterona",
            de: "Testosteronphenylpropionat",
            it: "fenilpropionato di testosterone",
            nl: "testosteronfenylpropionaat",
            pt: "fenilpropionato de testosterona",
            ru: "фенилпропионат тестостерона",
            ja: "テストステロンフェニルプロピオン酸エステル",
            zh: "苯丙酸睾酮",
            ko: "테스토스테론 페닐프로피오네이트",
            ar: "فينيل بروبيونات التستوستيرون",
            hi: "टेस्टोस्टेरोन फेनिलप्रोपियोनेट",
            id: "testosteron fenilpropionat",
            tr: "testosteron fenilpropiyonat",
            pl: "fenylopropionian testosteronu",
            sv: "testosteronfenylpropionat",
            da: "testosteronfenylpropionat",
            no: "testosteronfenylpropionat",
            cs: "testosteron fenylpropionát",
            hu: "tesztoszteron-fenilpropionát",
            vi: "testosterone phenylpropionate"
        },
        pubchemid: null,
        self_id: 'testosterone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        melting_point: [115, 116],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone cypionate",
        translations: {
            en: "testosterone cypionate",
            fr: "cypionate de testostérone",
            es: "cipionato de testosterona",
            de: "Testosteroncipionat",
            it: "cipionato di testosterone",
            nl: "testosteroncypionaat",
            pt: "cipionato de testosterona",
            ru: "ципионат тестостерона",
            ja: "テストステロンシピオン酸エステル",
            zh: "环戊丙酸睾酮",
            ko: "테스토스테론 사이피오네이트",
            ar: "سيبيونات التستوستيرون",
            hi: "टेस्टोस्टेरोन सिपियोनेट",
            id: "testosteron sipionat",
            tr: "testosteron sipiyonat",
            pl: "cypionian testosteronu",
            sv: "testosteroncipionat",
            da: "testosteroncipionat",
            no: "testosteroncipionat",
            cs: "testosteron cypionát",
            hu: "tesztoszteron-cipionát",
            vi: "testosterone cypionate"
        },
        pubchemid: null,
        self_id: 'testosterone_cypionate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [98, 102],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.84,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone enanthate",
        translations: {
            en: "testosterone enanthate",
            fr: "énanthate de testostérone",
            es: "enantato de testosterona",
            de: "Testosteronenanthat",
            it: "enantato di testosterone",
            nl: "testosteronenanthaat",
            pt: "enantato de testosterona",
            ru: "энантат тестостерона",
            ja: "テストステロンエナント酸エステル",
            zh: "庚酸睾酮",
            ko: "테스토스테론 에난테이트",
            ar: "إينونثات التستوستيرون",
            hi: "टेस्टोस्टेरोन एनन्थेट",
            id: "testosteron enantat",
            tr: "testosteron enantat",
            pl: "enantan testosteronu",
            sv: "testosteronenantat",
            da: "testosteronenantat",
            no: "testosteronenantat",
            cs: "testosteron enantát",
            hu: "tesztoszteron-enantát",
            vi: "testosterone enanthate"
        },
        pubchemid: null,
        self_id: 'testosterone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [32, 36],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.75,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone decanoate",
        translations: {
            en: "testosterone decanoate",
            fr: "décanoate de testostérone",
            es: "decanoato de testosterona",
            de: "Testosterondekanoat",
            it: "decanoato di testosterone",
            nl: "testosterondecanoaat",
            pt: "decanoato de testosterona",
            ru: "деканоат тестостерона",
            ja: "テストステロンデカン酸エステル",
            zh: "癸酸睾酮",
            ko: "테스토스테론 데카노에이트",
            ar: "ديكانوات التستوستيرون",
            hi: "टेस्टोस्टेरोन डिकानोएट",
            id: "testosteron dekanoat",
            tr: "testosteron dekanoat",
            pl: "dekanian testosteronu",
            sv: "testosterondekanoat",
            da: "testosterondekanoat",
            no: "testosterondekanoat",
            cs: "testosteron dekanoát",
            hu: "tesztoszteron-dekanoát",
            vi: "testosterone decanoate"
        },
        pubchemid: null,
        self_id: 'testosterone_decanoate',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [47, 49],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 300,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.78,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Testosterone undecanoate",
        translations: {
            en: "testosterone undecanoate",
            fr: "undécanoate de testostérone",
            es: "undecanoato de testosterona",
            de: "Testosteronundekanoat",
            it: "undecanoato di testosterone",
            nl: "testosteronundecanoaat",
            pt: "undecanoato de testosterona",
            ru: "ундеканоат тестостерона",
            ja: "テストステロンウンデカン酸エステル",
            zh: "十一酸睾酮",
            ko: "테스토스테론 운데카노에이트",
            ar: "أنديكانوات التستوستيرون",
            hi: "टेस्टोस्टेरोन अंडेकानोएट",
            id: "testosteron undecanoat",
            tr: "testosteron undekanoat",
            pl: "undekanian testosteronu",
            sv: "testosteronundekanoat",
            da: "testosteronundekanoat",
            no: "testosteronundekanoat",
            cs: "testosteron undekanoát",
            hu: "tesztoszteron-undekanoát",
            vi: "testosterone undecanoate"
        },
        pubchemid: null,
        self_id: 'testosterone_undecanoate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        melting_point: [59, 61],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 250,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.78,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Trenbolone base",
        translations: {
            en: "trenbolone base",
            fr: "trenbolone base",
            es: "trenbolona base",
            de: "Trenbolon-Base",
            it: "trenbolone base",
            nl: "trenbolonbasis",
            pt: "trenbolona base",
            ru: "основа тренболона",
            ja: "トレンボロンベース",
            zh: "群勃龙基础粉",
            ko: "트렌볼론 베이스",
            ar: "قاعدة ترينبولون",
            hi: "ट्रेनबोलोन बेस",
            id: "basis trenbolon",
            tr: "trenbolon bazı",
            pl: "baza trenbolonu",
            sv: "trenbolonbas",
            da: "trenbolon-base",
            no: "trenbolon-base",
            cs: "trenbolon báze",
            hu: "trenbolon bázis",
            vi: "trenbolone nền"
        },
        pubchemid: null,
        self_id: 'trenbolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [168, 172],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.7,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Trenbolone acetate",
        translations: {
            en: "trenbolone acetate",
            fr: "acétate de trenbolone",
            es: "acetato de trenbolona",
            de: "Trenbolonacetat",
            it: "acetato di trenbolone",
            nl: "trenbolonacetaat",
            pt: "acetato de trenbolona",
            ru: "ацетат тренболона",
            ja: "トレンボロン酢酸エステル",
            zh: "醋酸群勃龙",
            ko: "트렌볼론 아세테이트",
            ar: "أسيتات ترينبولون",
            hi: "ट्रेनबोलोन एसीटेट",
            id: "trenbolon asetat",
            tr: "trenbolon asetat",
            pl: "octan trenbolonu",
            sv: "trenbolonacetat",
            da: "trenbolonacetat",
            no: "trenbolonacetat",
            cs: "trenbolon acetát",
            hu: "trenbolon-acetát",
            vi: "trenbolone acetate"
        },
        pubchemid: null,
        self_id: 'trenbolone_acetate',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [140,144],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.6,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Trenbolone hexahydrobenzylcarbonate",
        translations: {
            en: "trenbolone hexahydrobenzylcarbonate",
            fr: "hexahydrobenzylcarbonate de trenbolone",
            es: "hexahidrobencilcarbonato de trenbolona",
            de: "Trenbolonhexahydrobenzylcarbonat",
            it: "esaidrobenzilcarbonato di trenbolone",
            nl: "trenbolonhexahydrobenzylcarbonaat",
            pt: "hexahidrobenzilcarbonato de trenbolona",
            ru: "гексагидробензилкарбонат тренболона",
            ja: "トレンボロンヘキサヒドロベンジルカーボネート",
            zh: "己氢苄基碳酸群勃龙酯",
            ko: "트렌볼론 헥사하이드로벤질카보네이트",
            ar: "هكسا هيدروبنزيل كربونات ترينبولون",
            hi: "ट्रेनबोलोन हेक्साहाइड्रोबेंज़िलकार्बोनेट",
            id: "trenbolon heksahidrobenzilkarbonat",
            tr: "trenbolon hekzahidrobenzilkarbonat",
            pl: "heksahydrobenzylowęglan trenbolonu",
            sv: "trenbolonhexahydrobensylkarbonat",
            da: "trenbolonhexahydrobenzylcarbonat",
            no: "trenbolonhexahydrobenzylkarbonat",
            cs: "trenbolon hexahydrobenzylkarbonát",
            hu: "trenbolon-hexahidrobenzilkarbonát",
            vi: "trenbolone hexahydrobenzylcarbonate"
        },
        pubchemid: null,
        self_id: 'trenbolone_hexahydrobenzylcarbonate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [183, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 75,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 9,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Trenbolone enanthate",
        translations: {
            en: "trenbolone enanthate",
            fr: "énanthate de trenbolone",
            es: "enantato de trenbolona",
            de: "Trenbolonenanthat",
            it: "enantato di trenbolone",
            nl: "trenbolonenanthaat",
            pt: "enantato de trenbolona",
            ru: "энантат тренболона",
            ja: "トレンボロンエナント酸エステル",
            zh: "庚酸群勃龙",
            ko: "트렌볼론 에난테이트",
            ar: "إينونثات ترينبولون",
            hi: "ट्रेनबोलोन एनन्थेट",
            id: "trenbolon enantat",
            tr: "trenbolon enantat",
            pl: "enantan trenbolonu",
            sv: "trenbolonenantat",
            da: "trenbolonenantat",
            no: "trenbolonenantat",
            cs: "trenbolon enantát",
            hu: "trenbolon-enantát",
            vi: "trenbolone enanthate"
        },
        pubchemid: null,
        self_id: 'trenbolone_enanthate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [72, 78],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Drostanolone propionate",
        translations: {
            en: "drostanolone propionate",
            fr: "propionate de drostanolone",
            es: "propionato de drostanolona",
            de: "Drostanolonpropionat",
            it: "propionato di drostanolone",
            nl: "drostanolonpropionaat",
            pt: "propionato de drostanolona",
            ru: "пропионат дростанолона",
            ja: "ドロスタノロンプロピオン酸エステル",
            zh: "丙酸屈他雄酮",
            ko: "드로스타놀론 프로피오네이트",
            ar: "بروبيونات دروستانولون",
            hi: "ड्रोस्टानोलोन प्रोपियोनेट",
            id: "drostanolon propionat",
            tr: "drostanolon propiyonat",
            pl: "propionian drostanolonu",
            sv: "drostanolonpropionat",
            da: "drostanolonpropionat",
            no: "drostanolonpropionat",
            cs: "drostanolon propionát",
            hu: "drosztanolon-propionát",
            vi: "drostanolone propionate"
        },
        pubchemid: null,
        self_id: 'drostanolone_propionate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [125, 127],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Drostanolone enanthate",
        translations: {
            en: "drostanolone enanthate",
            fr: "énanthate de drostanolone",
            es: "enantato de drostanolona",
            de: "Drostanolonenanthat",
            it: "enantato di drostanolone",
            nl: "drostanolonenantaat",
            pt: "enantato de drostanolona",
            ru: "энантат дростанолона",
            ja: "ドロスタノロンエナント酸エステル",
            zh: "庚酸屈他雄酮",
            ko: "드로스타놀론 에난테이트",
            ar: "إينونثات دروستانولون",
            hi: "ड्रोस्टानोलोन एनन्थेट",
            id: "drostanolon enantat",
            tr: "drostanolon enantat",
            pl: "enantan drostanolonu",
            sv: "drostanolonenantat",
            da: "drostanolonenantat",
            no: "drostanolonenantat",
            cs: "drostanolon enantát",
            hu: "drosztanolon-enantát",
            vi: "drostanolone enanthate"
        },
        pubchemid: null,
        self_id: 'drostanolone_enanthate',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [53, 56],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.7,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Methenolone acetate",
        translations: {
            en: "methenolone acetate",
            fr: "acétate de méthénolone",
            es: "acetato de metenolona",
            de: "Methenolonacetat",
            it: "acetato di metenolone",
            nl: "methenolonacetaat",
            pt: "acetato de metenolona",
            ru: "ацетат метенолона",
            ja: "メテノロン酢酸エステル",
            zh: "醋酸美替诺龙",
            ko: "메테놀론 아세테이트",
            ar: "أسيتات ميثينولون",
            hi: "मेथेनोलोन एसीटेट",
            id: "metenolon asetat",
            tr: "metenolon asetat",
            pl: "octan metenolonu",
            sv: "methenolonacetat",
            da: "methenolonacetat",
            no: "methenolonacetat",
            cs: "methenolon acetát",
            hu: "metenolon-acetát",
            vi: "methenolone acetate"
        },
        pubchemid: null,
        self_id: 'methenolone_acetate',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [141, 143],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 15,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Methenolone enanthate",
        translations: {
            en: "methenolone enanthate",
            fr: "énanthate de méthénolone",
            es: "enantato de metenolona",
            de: "Methenolonenanthat",
            it: "enantato di metenolone",
            nl: "methenolonenantaat",
            pt: "enantato de metenolona",
            ru: "энантат метенолона",
            ja: "メテノロンエナント酸エステル",
            zh: "庚酸美替诺龙",
            ko: "메테놀론 에난테이트",
            ar: "إينونثات ميثينولون",
            hi: "मेथेनोलोन एनन्थेट",
            id: "metenolon enantat",
            tr: "metenolon enantat",
            pl: "enantan metenolonu",
            sv: "methenolonenantat",
            da: "methenolonenantat",
            no: "methenolonenantat",
            cs: "methenolon enantát",
            hu: "metenolon-enantát",
            vi: "methenolone enanthate"
        },
        pubchemid: null,
        self_id: 'methenolone_enanthate',
        molecular_weight: 0,
        density: 1.0526315789473684,
        displacement: 0.95,
        melting_point: [66, 71],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 15,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Nandrolone base",
        translations: {
            en: "nandrolone base",
            fr: "nandrolone base",
            es: "nandrolona base",
            de: "Nandrolon-Base",
            it: "nandrolone base",
            nl: "nandrolonbasis",
            pt: "nandrolona base",
            ru: "основа нандролона",
            ja: "ナンドロロンベース",
            zh: "诺龙基础粉",
            ko: "난드롤론 베이스",
            ar: "قاعدة ناندرولون",
            hi: "नैंड्रोलोन बेस",
            id: "basis nandrolon",
            tr: "nandrolon bazı",
            pl: "baza nandrolonu",
            sv: "nandrolonbas",
            da: "nandrolon-base",
            no: "nandrolon-base",
            cs: "nandrolon báze",
            hu: "nandrolon bázis",
            vi: "nandrolone nền"
        },
        pubchemid: null,
        self_id: 'nandrolone_base',
        molecular_weight: 0,
        density: 1.1235955056179776,
        displacement: 0.89,
        melting_point: [120, 125],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 50,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Nandrolone phenylpropionate",
        translations: {
            en: "nandrolone phenylpropionate",
            fr: "phénylpropionate de nandrolone",
            es: "fenilpropionato de nandrolona",
            de: "Nandrolonphenylpropionat",
            it: "fenilpropionato di nandrolone",
            nl: "nandrolonfenylpropionaat",
            pt: "fenilpropionato de nandrolona",
            ru: "фенилпропионат нандролона",
            ja: "ナンドロロンフェニルプロピオン酸エステル",
            zh: "苯丙酸诺龙",
            ko: "난드롤론 페닐프로피오네이트",
            ar: "فينيل بروبيونات ناندرولون",
            hi: "नैंड्रोलोन फेनिलप्रोपियोनेट",
            id: "nandrolon fenilpropionat",
            tr: "nandrolon fenilpropiyonat",
            pl: "fenylopropionian nandrolonu",
            sv: "nandrolonfenylpropionat",
            da: "nandrolonfenylpropionat",
            no: "nandrolonfenylpropionat",
            cs: "nandrolon fenylpropionát",
            hu: "nandrolon-fenilpropionát",
            vi: "nandrolone phenylpropionate"
        },
        pubchemid: null,
        self_id: 'nandrolone_phenylpropionate',
        molecular_weight: 0,
        density: 1.1363636363636365,
        displacement: 0.88,
        melting_point: [85, 87],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 100,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.25,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Nandrolone decanoate",
        translations: {
            en: "nandrolone decanoate",
            fr: "décanoate de nandrolone",
            es: "decanoato de nandrolona",
            de: "Nandrolondekanoat",
            it: "decanoato di nandrolone",
            nl: "nandrolondecanoaat",
            pt: "decanoato de nandrolona",
            ru: "деканоат нандролона",
            ja: "ナンドロロンデカン酸エステル",
            zh: "癸酸诺龙",
            ko: "난드롤론 데카노에이트",
            ar: "ديكانوات ناندرولون",
            hi: "नैंड्रोलोन डिकानोएट",
            id: "nandrolon dekanoat",
            tr: "nandrolon dekanoat",
            pl: "dekanian nandrolonu",
            sv: "nandrolondekanoat",
            da: "nandrolondekanoat",
            no: "nandrolondekanoat",
            cs: "nandrolon dekanoát",
            hu: "nandrolon-dekanoát",
            vi: "nandrolone decanoate"
        },
        pubchemid: null,
        self_id: 'nandrolone_decanoate',
        molecular_weight: 428.63,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [30, 35],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 200,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0.92,
    },
    // Source: https://sitem.herts.ac.uk/aeru/vsdb/Reports/3750.htm
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Boldenone base",
        cas_no: '846-48-0',
        log_p: 2.3,
        translations: {
            en: "boldenone base",
            fr: "boldénone base",
            es: "boldenona base",
            de: "Boldenon-Base",
            it: "boldenone base",
            nl: "boldenonbasis",
            pt: "boldenona base",
            ru: "основа болденона",
            ja: "ボルデノンベース",
            zh: "博尔德酮基础粉",
            ko: "볼데논 베이스",
            ar: "قاعدة بولدينون",
            hi: "बोल्डेनोन बेस",
            id: "basis boldenon",
            tr: "boldenon bazı",
            pl: "baza boldenonu",
            sv: "boldenonbas",
            da: "boldenon-base",
            no: "boldenon-base",
            cs: "boldenon báze",
            hu: "boldenon bázis",
            vi: "boldenone nền"
        },
        pubchemid: null,
        self_id: 'boldenone_base',
        molecular_weight: 286.4,
        density: 1.14,
        displacement: 0.91,
        melting_point: [168.1],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
    },
    // Source: https://sitem.herts.ac.uk/aeru/vsdb/Reports/3751.htm
    // Source: https://www.chemsrc.com/en/cas/2363-59-9_754966.html
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Boldenone acetate",
        cas_no:  '2363-59-9',
        log_p: 4.39,
        translations: {
            en: "boldenone acetate",
            fr: "acétate de boldénone",
            es: "acetato de boldenona",
            de: "Boldenonacetat",
            it: "acetato di boldenone",
            nl: "boldenonacetaat",
            pt: "acetato de boldenona",
            ru: "ацетат болденона",
            ja: "ボルデノンアセテート",
            zh: "醋酸博尔德酮",
            ko: "볼데논 아세테이트",
            ar: "أسيتات بولدينون",
            hi: "बोल्डेनोन एसीटेट",
            id: "boldenon asetat",
            tr: "boldenon asetat",
            pl: "octan boldenonu",
            sv: "boldenonacetat",
            da: "boldenonacetat",
            no: "boldenonacetat",
            cs: "boldenon acetát",
            hu: "boldenon-acetát",
            vi: "boldenone acetate"
        },
        pubchemid: null,
        self_id: 'boldenone_acetate',
        molecular_weight: 328.4,
        density: 1.1,
        displacement: 0.95,
        melting_point: [0],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.65,
    },
    // Source: https://sitem.herts.ac.uk/aeru/vsdb/Reports/2967.htm
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Boldenone undecylenate",
        cas_no:  '13103-34-9',
        log_p: 3.1,
        translations: {
            en: "boldenone undecylenate",
            fr: "undécylénate de boldénone",
            es: "undecilenato de boldenona",
            de: "Boldenonundecylenat",
            it: "undecilenato di boldenone",
            nl: "boldenonundecyleenaat",
            pt: "undecilenato de boldenona",
            ru: "ундесиленат болденона",
            ja: "ボルデノンウンデシレン酸エステル",
            zh: "十一烯酸博尔德酮",
            ko: "볼데논 운데실레네이트",
            ar: "أنديسيلينات بولدينون",
            hi: "बोल्डेनोन अन्डेसिलिनेट",
            id: "boldenon undecilenat",
            tr: "boldenon undesilenat",
            pl: "undecylenian boldenonu",
            sv: "boldenonundecylenat",
            da: "boldenonundecylenat",
            no: "boldenonundecylenat",
            cs: "boldenon undecylenát",
            hu: "boldenon-undecilénát",
            vi: "boldenone undecylenate"
        },
        pubchemid: null,
        self_id: 'boldenone_undecylenate',
        molecular_weight: 452.67,
        density: 1.055,
        displacement: 0.95,
        melting_point: [0],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.65,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Dihydroboldenone cypionate",
        translations: {
            en: "dihydroboldenone cypionate",
            fr: "cypionate de dihydroboldénone",
            es: "cipionato de dihidroboldenona",
            de: "Dihydroboldenoncypionat",
            it: "cipionato di diidroboldenone",
            nl: "dihydroboldenoncypionaat",
            pt: "cipionato de dihidroboldenona",
            ru: "ципионат дигидроболденона",
            ja: "ジヒドロボルデノンシピオン酸エステル",
            zh: "环戊丙酸二氢博尔德酮",
            ko: "디하이드로볼데논 사이피오네이트",
            ar: "سيبيونات ديهدروبوليينون",
            hi: "डाइहाइड्रोबोल्डेनोन सिपियोनेट",
            id: "dihidroboldenon sipionat",
            tr: "dihidroboldenon sipiyonat",
            pl: "cypionian dihydroboldenonu",
            sv: "dihydroboldenoncypionat",
            da: "dihydroboldenoncypionat",
            no: "dihydroboldenoncypionat",
            cs: "dihydroboldenon cypionát",
            hu: "dihidroboldenon-cipionát",
            vi: "dihydroboldenone cypionate"
        },
        pubchemid: null,
        self_id: 'dihydroboldenone_cypionate',
        molecular_weight: 0,
        density: 1.0309278350515465,
        displacement: 0.97,
        melting_point: [192, 196],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Dianabol",
        cas_no: '72-63-9',
        log_p: 4.04,
        translations: {
            en: "Dianabol",
            fr: "Dianabol",
            es: "Dianabol",
            de: "Dianabol",
            it: "Dianabol",
            nl: "Dianabol",
            pt: "Dianabol",
            ru: "Дианабол",
            ja: "ダイアナボル",
            zh: "大力补",
            ko: "다이아나볼",
            ar: "ديانابول",
            hi: "डायनाबोल",
            id: "Dianabol",
            tr: "Dianabol",
            pl: "Dianabol",
            sv: "Dianabol",
            da: "Dianabol",
            no: "Dianabol",
            cs: "Dianabol",
            hu: "Dianabol",
            vi: "Dianabol"
        },
        pubchemid: null,
        self_id: 'dianabol',
        molecular_weight: 300.435,
        density: 1.075268817204301,
        displacement: 0.93,
        melting_point: [164, 167],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Anadrol",
        cas_no: '434-07-1',
        log_p: 4.22,
        translations: {
            en: "Anadrol",
            fr: "Anadrol",
            es: "Anadrol",
            de: "Anadrol",
            it: "Anadrol",
            nl: "Anadrol",
            pt: "Anadrol",
            ru: "Анадрол",
            ja: "アナドロール",
            zh: "康力龙",
            ko: "아나드롤",
            ar: "أنادرول",
            hi: "एनाड्रोल",
            id: "Anadrol",
            tr: "Anadrol",
            pl: "Anadrol",
            sv: "Anadrol",
            da: "Anadrol",
            no: "Anadrol",
            cs: "Anadrol",
            hu: "Anadrol",
            vi: "Anadrol"
        },
        pubchemid: null,
        self_id: 'anadrol',
        molecular_weight: 332.477,
        density: 1.1627906976744187,
        displacement: 0.86,
        melting_point: [177, 180],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.98,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Anavar",
        translations: {
            en: "Anavar",
            fr: "Anavar",
            es: "Anavar",
            de: "Anavar",
            it: "Anavar",
            nl: "Anavar",
            pt: "Anavar",
            ru: "Анавар",
            ja: "アナバー",
            zh: "安纳瓦",
            ko: "아나바",
            ar: "أنافار",
            hi: "एनावर",
            id: "Anavar",
            tr: "Anavar",
            pl: "Anavar",
            sv: "Anavar",
            da: "Anavar",
            no: "Anavar",
            cs: "Anavar",
            hu: "Anavar",
            vi: "Anavar"
        },
        pubchemid: null,
        self_id: 'anavar',
        molecular_weight: 0,
        density: 1.1111111111111112,
        displacement: 0.9,
        melting_point: [235, 238],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 6.5,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Turinabol",
        translations: {
            en: "Turinabol",
            fr: "Turinabol",
            es: "Turinabol",
            de: "Turinabol",
            it: "Turinabol",
            nl: "Turinabol",
            pt: "Turinabol",
            ru: "Туринабол",
            ja: "トリナボル",
            zh: "图林博",
            ko: "투리나볼",
            ar: "تورينابول",
            hi: "ट्यूरिनाबोल",
            id: "Turinabol",
            tr: "Turinabol",
            pl: "Turinabol",
            sv: "Turinabol",
            da: "Turinabol",
            no: "Turinabol",
            cs: "Turinabol",
            hu: "Turinabol",
            vi: "Turinabol"
        },
        pubchemid: null,
        self_id: 'turinabol',
        molecular_weight: 0,
        density: 1.2048192771084338,
        displacement: 0.83,
        melting_point: [225, 230],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 8.4,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Winstrol",
        cas_no: '10418-03-8',
        log_p: 5.53,
        translations: {
            en: "Winstrol",
            fr: "Winstrol",
            es: "Winstrol",
            de: "Winstrol",
            it: "Winstrol",
            nl: "Winstrol",
            pt: "Winstrol",
            ru: "Винстрол",
            ja: "ウィンストロール",
            zh: "康力龙",
            ko: "윈스트롤",
            ar: "وينسترول",
            hi: "विन्स्ट्रोल",
            id: "Winstrol",
            tr: "Winstrol",
            pl: "Winstrol",
            sv: "Winstrol",
            da: "Winstrol",
            no: "Winstrol",
            cs: "Winstrol",
            hu: "Winstrol",
            vi: "Winstrol"
        },
        pubchemid: null,
        self_id: 'winstrol',
        molecular_weight: 328.492,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [228, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 1.95,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Proviron",
        translations: {
            en: "Proviron",
            fr: "Proviron",
            es: "Proviron",
            de: "Proviron",
            it: "Proviron",
            nl: "Proviron",
            pt: "Proviron",
            ru: "Провирон",
            ja: "プロビロン",
            zh: "普维雄",
            ko: "프로비론",
            ar: "بروفيرون",
            hi: "प्रोविरोन",
            id: "Proviron",
            tr: "Proviron",
            pl: "Proviron",
            sv: "Proviron",
            da: "Proviron",
            no: "Proviron",
            cs: "Proviron",
            hu: "Proviron",
            vi: "Proviron"
        },
        pubchemid: null,
        self_id: 'proviron',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [206, 210],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 3,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Halotestin",
        translations: {
            en: "Halotestin",
            fr: "Halotestin",
            es: "Halotestin",
            de: "Halotestin",
            it: "Halotestin",
            nl: "Halotestin",
            pt: "Halotestin",
            ru: "Халотестин",
            ja: "ハロテスチン",
            zh: "哈洛泰斯汀",
            ko: "할로테스틴",
            ar: "هالوتستين",
            hi: "हैलोटेस्टिन",
            id: "Halotestin",
            tr: "Halotestin",
            pl: "Halotestin",
            sv: "Halotestin",
            da: "Halotestin",
            no: "Halotestin",
            cs: "Halotestin",
            hu: "Halotestin",
            vi: "Halotestin"
        },
        pubchemid: null,
        self_id: 'halotestin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [238, 242],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 39.8,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Methyltrienolone",
        translations: {
            en: "methyltrienolone",
            fr: "méthyltriénolone",
            es: "metiltrienolona",
            de: "Methyltrienolon",
            it: "metiltrienolone",
            nl: "methyltrienolon",
            pt: "metiltrienolona",
            ru: "метилтриенолон",
            ja: "メチルトリエノロン",
            zh: "甲基三烯诺龙",
            ko: "메틸트리에놀론",
            ar: "ميثيلترينولون",
            hi: "मेथिलट्रिएनोलोन",
            id: "metiltrienolon",
            tr: "metiltrienolon",
            pl: "metyltrienolon",
            sv: "metyltrienolon",
            da: "methyltrienolon",
            no: "methyltrienolon",
            cs: "methyltrienolon",
            hu: "metiltrienolon",
            vi: "methyltrienolone"
        },
        pubchemid: null,
        self_id: 'methyltrienolone',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [165, 170],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Methyl-1-Testosterone",
        translations: {
            en: "methyl-1-testosterone",
            fr: "méthyl-1-testostérone",
            es: "metil-1-testosterona",
            de: "Methyl-1-Testosteron",
            it: "metil-1-testosterone",
            nl: "methyl-1-testosteron",
            pt: "metil-1-testosterona",
            ru: "метил-1-тестостерон",
            ja: "メチル-1-テストステロン",
            zh: "甲基-1-睾酮",
            ko: "메틸-1-테스토스테론",
            ar: "ميثيل-1-تستوستيرون",
            hi: "मेथिल-1-टेस्टोस्टेरोन",
            id: "metil-1-testosteron",
            tr: "metil-1-testosteron",
            pl: "metyl-1-testosteron",
            sv: "metyl-1-testosteron",
            da: "methyl-1-testosteron",
            no: "methyl-1-testosteron",
            cs: "methyl-1-testosteron",
            hu: "metil-1-tesztoszteron",
            vi: "methyl-1-testosterone"
        },
        pubchemid: null,
        self_id: 'methyl,1,testosterone',
        molecular_weight: 0,
        density: 1.0869565217391304,
        displacement: 0.92,
        melting_point: [154, 155],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Superdrol",
        translations: {
            en: "Superdrol",
            fr: "Superdrol",
            es: "Superdrol",
            de: "Superdrol",
            it: "Superdrol",
            nl: "Superdrol",
            pt: "Superdrol",
            ru: "Супердрол",
            ja: "スーパードロール",
            zh: "超级卓尔",
            ko: "슈퍼드롤",
            ar: "سوبردرول",
            hi: "सुपरड्रोल",
            id: "Superdrol",
            tr: "Superdrol",
            pl: "Superdrol",
            sv: "Superdrol",
            da: "Superdrol",
            no: "Superdrol",
            cs: "Superdrol",
            hu: "Superdrol",
            vi: "Superdrol"
        },
        pubchemid: null,
        self_id: 'superdrol',
        molecular_weight: 0,
        density: 1.0416666666666667,
        displacement: 0.96,
        melting_point: [148, 150],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 8.76,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Methyl-DHT",
        translations: {
            en: "methyl-DHT",
            fr: "méthyl-DHT",
            es: "metil-DHT",
            de: "Methyl-DHT",
            it: "metil-DHT",
            nl: "methyl-DHT",
            pt: "metil-DHT",
            ru: "метил-ДГТ",
            ja: "メチルDHT",
            zh: "甲基DHT",
            ko: "메틸-DHT",
            ar: "ميثيل-DHT",
            hi: "मेथिल-DHT",
            id: "metil-DHT",
            tr: "metil-DHT",
            pl: "metyl-DHT",
            sv: "metyl-DHT",
            da: "methyl-DHT",
            no: "methyl-DHT",
            cs: "methyl-DHT",
            hu: "metil-DHT",
            vi: "methyl-DHT"
        },
        pubchemid: null,
        self_id: 'methyl,dht',
        molecular_weight: 0,
        density: 1.0638297872340425,
        displacement: 0.94,
        melting_point: [185, 192],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Aromasin",
        translations: {
            en: "Aromasin",
            fr: "Aromasin",
            es: "Aromasin",
            de: "Aromasin",
            it: "Aromasin",
            nl: "Aromasin",
            pt: "Aromasin",
            ru: "Аромазин",
            ja: "アロマシン",
            zh: "阿诺新",
            ko: "아로마신",
            ar: "أروماسين",
            hi: "अरोमासिन",
            id: "Aromasin",
            tr: "Aromasin",
            pl: "Aromasin",
            sv: "Aromasin",
            da: "Aromasin",
            no: "Aromasin",
            cs: "Aromasin",
            hu: "Aromasin",
            vi: "Aromasin"
        },
        pubchemid: null,
        self_id: 'aromasin',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [153, 157],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 3,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Arimidex",
        translations: {
            en: "Arimidex",
            fr: "Arimidex",
            es: "Arimidex",
            de: "Arimidex",
            it: "Arimidex",
            nl: "Arimidex",
            pt: "Arimidex",
            ru: "Аримидекс",
            ja: "アリミデックス",
            zh: "阿里米德",
            ko: "아리미덱스",
            ar: "أريميدكس",
            hi: "अरिमिडेक्स",
            id: "Arimidex",
            tr: "Arimidex",
            pl: "Arimidex",
            sv: "Arimidex",
            da: "Arimidex",
            no: "Arimidex",
            cs: "Arimidex",
            hu: "Arimidex",
            vi: "Arimidex"
        },
        pubchemid: null,
        self_id: 'arimidex',
        molecular_weight: 0,
        density: 1.0989010989010988,
        displacement: 0.91,
        melting_point: [81, 82],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 3.5,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Letrozole",
        translations: {
            en: "letrozole",
            fr: "létrozole",
            es: "letrozol",
            de: "Letrozol",
            it: "letrozolo",
            nl: "letrozol",
            pt: "letrozol",
            ru: "летрозол",
            ja: "レトロゾール",
            zh: "来曲唑",
            ko: "레트로졸",
            ar: "ليتروزول",
            hi: "लेट्रोज़ोल",
            id: "letrozole",
            tr: "letrozol",
            pl: "letrozol",
            sv: "letrozol",
            da: "letrozol",
            no: "letrozol",
            cs: "letrozol",
            hu: "letrozol",
            vi: "letrozole"
        },
        pubchemid: null,
        self_id: 'letrozole',
        molecular_weight: 0,
        density: 1.2195121951219512,
        displacement: 0.82,
        melting_point: [181, 186],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Pramipexole",
        translations: {
            en: "pramipexole",
            fr: "pramipexole",
            es: "pramipexol",
            de: "Pramipexol",
            it: "pramipexolo",
            nl: "pramipexol",
            pt: "pramipexol",
            ru: "прамипексол",
            ja: "プラミペキソール",
            zh: "普拉克索",
            ko: "프라미펙솔",
            ar: "براميبيكسول",
            hi: "प्रामिपेक्सोल",
            id: "pramipexole",
            tr: "pramipeksol",
            pl: "pramipeksol",
            sv: "pramipexol",
            da: "pramipexol",
            no: "pramipexol",
            cs: "pramipexol",
            hu: "pramipexol",
            vi: "pramipexole"
        },
        pubchemid: null,
        self_id: 'pramipexole',
        molecular_weight: 0,
        density: 1.1764705882352942,
        displacement: 0.85,
        melting_point: [118, 122],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Tamoxifen",
        translations: {
            en: "tamoxifen",
            fr: "tamoxifène",
            es: "tamoxifeno",
            de: "Tamoxifen",
            it: "tamoxifene",
            nl: "tamoxifen",
            pt: "tamoxifeno",
            ru: "тамоксифен",
            ja: "タモキシフェン",
            zh: "他莫昔芬",
            ko: "타목시펜",
            ar: "تاموكسيفين",
            hi: "टैमोक्सीफेन",
            id: "tamoxifen",
            tr: "tamoksifen",
            pl: "tamoksyfen",
            sv: "tamoxifen",
            da: "tamoxifen",
            no: "tamoxifen",
            cs: "tamoxifen",
            hu: "tamoxifen",
            vi: "tamoxifen"
        },
        pubchemid: null,
        self_id: 'tamoxifen',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        melting_point: [143, 146],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "Clomiphene",
        translations: {
            en: "clomiphene",
            fr: "clomifène",
            es: "clomifeno",
            de: "Clomifen",
            it: "clomifene",
            nl: "clomifeen",
            pt: "clomifeno",
            ru: "кломифен",
            ja: "クロミフェン",
            zh: "克罗米芬",
            ko: "클로미펜",
            ar: "كلوميفين",
            hi: "क्लोमीफीन",
            id: "clomiphene",
            tr: "klomifen",
            pl: "klomifen",
            sv: "klomifen",
            da: "clomifen",
            no: "klomifen",
            cs: "klomifen",
            hu: "klomifén",
            vi: "clomiphene"
        },
        pubchemid: null,
        self_id: 'clomiphene',
        molecular_weight: 0,
        density: 1,
        displacement: 1,
        melting_point: [116, 118],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 0,
    },
    {
        id: crypto.randomUUID(),
        class: 'ingredient',
        name: "YK11 (experimental)",
        translations: {
            en: "YK11",
            fr: "YK11",
            es: "YK11",
            de: "YK11",
            it: "YK11",
            nl: "YK11",
            pt: "YK11",
            ru: "YK-11",
            ja: "ワイケー11",
            zh: "YK11",
            ko: "와이케이11",
            ar: "واي كيه 11",
            hi: "वाईके11",
            id: "YK11",
            tr: "YK11",
            pl: "YK11",
            sv: "YK11",
            da: "YK11",
            no: "YK11",
            cs: "YK11",
            hu: "YK11",
            vi: "YK11"
        },
        pubchemid: null,
        cas_no:  '1370003-76-1',
        self_id: 'yk11',
        molecular_weight: 430.53,
        density: 1.22,
        displacement: 0.82,
        melting_point: [564.4],
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 2,
    },
    {
        id: "crypto.randomUUID()",
        class: "ingredient",
        name: "SLU-PP-332 (experimental)",
        translations: {
            en: "SLU-PP-332",
            fr: "SLU-PP-332",
            es: "SLU-PP-332",
            de: "SLU-PP-332",
            it: "SLU-PP-332",
            nl: "SLU-PP-332",
            pt: "SLU-PP-332",
            ru: "SLU-PP-332",
            ja: "SLU-PP-332",
            zh: "SLU-PP-332",
            ko: "SLU-PP-332",
            ar: "SLU-PP-332",
            hi: "SLU-PP-332",
            id: "SLU-PP-332",
            tr: "SLU-PP-332",
            pl: "SLU-PP-332",
            sv: "SLU-PP-332",
            da: "SLU-PP-332",
            no: "SLU-PP-332",
            cs: "SLU-PP-332",
            hu: "SLU-PP-332",
            vi: "SLU-PP-332"
        },
        pubchemid: 5338394,
        cas_no: "303760-60-3",
        self_id: "slu-pp-332",
        molecular_weight: 290.32,
        density: 1.20,
        displacement: 0.83,
        melting_point: 500, // made up
        mls: 0,
        grams: 0,
        v_v_percent: 0,
        mg_per_ml: 0,
        purity: 100,
        basis: "mg_per_ml",
        input: 0,
        qsMode: false,
        pricePerUnit: 2
    }
]


var solubility = [
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Long Length Esters',
        self_id: 'long_length_esters',
        low_solvent_range: [200, 300], // 0-10%
        medium_solvent_range: [300, 400], // 20-30%
        high_solvent_range: [400, 500], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_decanoate',
            'testosterone_undecanoate',
            'dihydroboldenone_undecylenate',
            'nandrolone_decanoate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Medium Length Esters',
        self_id: 'medium_length_esters',
        low_solvent_range: [100, 150], // 0-10%
        medium_solvent_range: [150, 250], // 20-30%
        high_solvent_range: [250, 350], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_cypionate',
            'testosterone_enanthate',
            'testosterone_phenylpropionate',
            'nandrolone_phenylpropionate',
            'dihydroboldenone_cypionate',
            'drostanolone_enanthate',
            'methenolone_enanthate',
        ]
    },
    {
        id: crypto.randomUUID(),
        class: 'solubility',
        name: 'Short Length Esters',
        self_id: 'short_length_esters',
        low_solvent_range: [0, 50], // 0-10%
        medium_solvent_range: [50, 100], // 20-30%
        high_solvent_range: [100, 150], // 30-50%
        co_solvent_self_id: 'benzyl_alcohol',
        member_self_ids: [
            'testosterone_acetate',
            'testosterone_propionate',
            'trenbolone_acetate',
            'methenolone_acetate',
        ]
    }
]