var recipes = [
    {
        id: crypto.randomUUID(),
        name: "Bayer Primo Testo Depot 250mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients:    ["castor"],
        excipientPercentages: [44.5],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
    },
    {
        id: crypto.randomUUID(),
        name: "Bayer Rimobolan (primo) 100mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 36.261180679785326],
        excipients:    ["castor"],
        excipientPercentages: [52.238819320214674],
        compounds: ["methenolone_enanthate"],
        compoundConcentration: [100],
    },
    {
        // Source: https://www.medicines.org.uk/emc/files/pil.14631.pdf
        id: crypto.randomUUID(),
        name: "Bayer Nebido 250mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 44.73],
        excipients:    ["castor"],
        excipientPercentages: [29.020000000000007],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [250],
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07
        id: crypto.randomUUID(),
        name: "DELESTROGEN Estradiol Valerate 10mg/mL",
        solvents: ["chlorobutanol"],
        solventPercentages: [0.76],
        excipients:    ["sesame"],
        excipientPercentages: [98.33090909090909],
        compounds: ["estradiol_valerate"],
        compoundConcentration: [10],
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07
        id: crypto.randomUUID(),
        name: "DELESTROGEN Estradiol Valerate 40mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 40],
        excipients:    ["castor"],
        excipientPercentages: [54.36363636363636],
        compounds: ["estradiol_valerate"],
        compoundConcentration: [40],
    },
    {
        // Source: https://www.drugs.com/vet/equipoise.html
        id: crypto.randomUUID(),
        name: "Equipoise 50mg/mL",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [3],
        excipients:    ["sesame"],
        excipientPercentages: [92.260663507109],
        compounds: ["boldenone_undecylenate"],
        compoundConcentration: [50],
    },
    {
        id: crypto.randomUUID(),
        name: "Cytex Test Cyp 100mg/mL",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [2],
        excipients:    ["ethyl_oleate"],
        excipientPercentages: [88.9],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [100],
    },
    {
        id: crypto.randomUUID(),
        name: "DECA-DURABOLIN 100mg/mL",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [10],
        excipients:    ["arachis"],
        excipientPercentages: [80.4],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [100],
    },
    {
        id: crypto.randomUUID(),
        name: "PARABOLAN 50mg/mL",
        solvents: ["benzyl_alcohol", "ethanol"],
        solventPercentages: [4.79,3.82],
        excipients:    ["arachis"],
        excipientPercentages: [86.84],
        compounds: ["trenbolone_hexahydrobenzylcarbonate"],
        compoundConcentration: [50],
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=a586b484-1b46-40b9-9508-fd28002ad383&type=display
        id: crypto.randomUUID(),
        name: "Watson Deca 200mg/mL",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [5],
        excipients:    ["sesame"],
        excipientPercentages: [75.8],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [200],
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=82a98132-9d5f-40a5-8c4f-f52f2a5de60e
        id: crypto.randomUUID(),
        name: "Testosterone Enanthate (Eugia) 200mg/mL",
        solvents: ["chlorobutanol"],
        solventPercentages: [0.5],
        excipients:    ["sesame"],
        excipientPercentages: [80.7],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source: https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf
        id: crypto.randomUUID(),
        name: "SUSTANON 250mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2,10],
        excipients:    ["arachis"],
        excipientPercentages: [64.78252336448598],
        compounds: ["testosterone_propionate", "testosterone_phenylpropionate", "testosterone_isocaproate", "testosterone_decanoate"],
        compoundConcentration: [30,60,60,100],
    },
    {
        // Source: https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf
        id: crypto.randomUUID(),
        name: "Testoboon CP 250mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [0.91, 22.362],
        excipients:    ["arachis"],
        excipientPercentages: [53.977999999999994],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
    },
    {
        id: crypto.randomUUID(),
        name: "Photon's No G TNE 100mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients:    ["castor"],
        excipientPercentages: [59.1],
        compounds: ["testosterone_base"],
        compoundConcentration: [100],
    },
    {
        id: crypto.randomUUID(),
        name: "Bananafeet's No G DHEA 50mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [6,30],
        excipients:    ["castor"],
        excipientPercentages: [59.23809523809524],
        compounds: ["dhea_base"],
        compoundConcentration: [50],
    },
    {
        id: crypto.randomUUID(),
        name: "OEP's No G Anadrol 50mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.4375, 42.9299],
        excipients:    ["castor"],
        excipientPercentages: [51.3325],
        compounds: ["anadrol"],
        compoundConcentration: [50],
    },
    {
        id: crypto.randomUUID(),
        name: "Injectable Winstrol 50mg/mL",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [10, 40],
        excipients:    ["castor"],
        excipientPercentages: [45.449999999999996],
        compounds: ["winstrol"],
        compoundConcentration: [50],
    },
    {
        // original is weak. made it a bit stronger (double)
        // source https://web.archive.org/web/20210126120007/https://steroid.to/sten-testosterone-cypionate-propionate
        id: crypto.randomUUID(),
        name: "STEN recipe",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2.5, 20],
        excipients:    ["arachis"],
        excipientPercentages: [66.4952380952381],
        compounds: ["dhea_base", "testosterone_propionate", "testosterone_cypionate"],
        compoundConcentration: [20, 25, 75],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test D 350mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [34.900000000000006],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [350],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Mast E 200mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [49.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's NPP 150mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [55.3],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [150],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test D 500mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [10.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test Iso 400mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [21.116822429906534],
        compounds: ["testosterone_isocaproate"],
        compoundConcentration: [400],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test C",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Deca",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [59.30],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren E",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["trenbolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren A",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [70],
        compounds: ["trenbolone_acetate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless NPP",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [69.7],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test Prop",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [69.4],
        compounds: ["testosterone_propionate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless EQ 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 18],
        excipients:    ["MCT"],
        excipientPercentages: [33],
        compounds: ["boldenone_undecylenate"],
        compoundConcentration: [500],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Mast E 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 15],
        excipients:    ["MCT"],
        excipientPercentages: [64.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test E 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients:    ["MCT"],
        excipientPercentages: [65],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Primo E 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients:    ["MCT"],
        excipientPercentages: [69.5],
        compounds: ["methenolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test D 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 24],
        excipients:    ["MCT"],
        excipientPercentages: [26.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients:    ["MCT"],
        excipientPercentages: [54.099999999999994],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test C 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients:    ["MCT"],
        excipientPercentages: [50.75],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Mast E 300",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 22],
        excipients:    ["MCT"],
        excipientPercentages: [48.3],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [300],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [34.25],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 350",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 50],
        excipients:    ["castor"],
        excipientPercentages: [14.550000000000011],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [350],
    },
];
