var recipes = [
    {
        id: crypto.randomUUID(),
        index: 0,
        name: "Primo Testo Depot",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients:    ["castor"],
        excipientPercentages: [44.5],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
    },
    {
        id: crypto.randomUUID(),
        index: 1 ,
        name: "Cytex Test Cyp",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [2],
        excipients:    ["ethyl_oleate"],
        excipientPercentages: [88.9],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [100],
    },
    {
        id: crypto.randomUUID(),
        index: 2,
        name: "Watson Deca 100",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [10],
        excipients:    ["cottonseed"],
        excipientPercentages: [80.4],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [100],
    },
    {
        // Source: https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf
        id: crypto.randomUUID(),
        index: 3,
        name: "SUSTANON 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [10],
        excipients:    ["arachis"],
        excipientPercentages: [66.78252336448598],
        compounds: ["testosterone_propionate", "testosterone_phenylpropionate", "testosterone_isocaproate", "testosterone_decanoate"],
        compoundConcentration: [30,60,60,100],
    },
    {
        // Source: https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf
        id: crypto.randomUUID(),
        index: 4,
        name: "Testoboon CP 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [0.91, 22.362],
        excipients:    ["arachis"],
        excipientPercentages: [53.977999999999994],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
    },
    {
        id: crypto.randomUUID(),
        index: 5,        name: "Photon's No G TNE",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients:    ["castor"],
        excipientPercentages: [59.1],
        compounds: ["testosterone_base"],
        compoundConcentration: [100],
    },
    {
        id: crypto.randomUUID(),
        index: 6,        name: "Bananafeet's No G DHEA",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [6, 30],
        excipients:    ["castor"],
        excipientPercentages: [59.24],
        compounds: ["dhea_base"],
        compoundConcentration: [50],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        index: 7,
        name: "Narta's Test D 350mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [34.900000000000006],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [350],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        index: 8,
        name: "Narta's Mast E 200mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [49.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        index: 9,
        name: "Narta's NPP 150mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients:    ["castor"],
        excipientPercentages: [55.3],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [150],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        index: 10,
        name: "Narta's Test D 500mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [10.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        index: 11,
        name: "Narta's Test Iso 400mg/ml",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [21.116822429906534],
        compounds: ["testosterone_isocaproate"],
        compoundConcentration: [400],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test C",
        index: 12,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren E",
        index: 13,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["trenbolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren A",
        index: 14,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [70],
        compounds: ["trenbolone_acetate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless NPP",
        index: 15,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [69.7],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test Prop",
        index: 16,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients:    ["MCT"],
        excipientPercentages: [69.4],
        compounds: ["testosterone_propionate"],
        compoundConcentration: [100],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless EQ 500",
        index: 17,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 18],
        excipients:    ["MCT"],
        excipientPercentages: [33],
        compounds: ["boldenone_undecylenate"],
        compoundConcentration: [500],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Mast E 200",
        index: 18,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 15],
        excipients:    ["MCT"],
        excipientPercentages: [64.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test E 250",
        index: 19,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients:    ["MCT"],
        excipientPercentages: [65],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Primo E 200",
        index: 20,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients:    ["MCT"],
        excipientPercentages: [69.5],
        compounds: ["methenolone_enanthate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test D 500",
        index: 21,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 24],
        excipients:    ["MCT"],
        excipientPercentages: [26.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 200",
        index: 22,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients:    ["MCT"],
        excipientPercentages: [54.099999999999994],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [200],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test C 250",
        index: 23,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients:    ["MCT"],
        excipientPercentages: [50.75],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Mast E 300",
        index: 24,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 22],
        excipients:    ["MCT"],
        excipientPercentages: [48.3],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [300],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 250",
        index: 25,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients:    ["castor"],
        excipientPercentages: [34.25],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [250],
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 350",
        index: 26,
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 50],
        excipients:    ["castor"],
        excipientPercentages: [14.550000000000011],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [350],
    },
];