var recipes = [
    {
        id: crypto.randomUUID(),
        name: "Bacteriostatic Water",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [0.9],
        excipients: ["sterile-water-for-injection"],
        excipientPercentages: [99.1],
        compounds: [],
        compoundConcentration: [],
        blurb: "A standard bacteriostatic water formulation using sterile water with benzyl alcohol as a preservative. Commonly used as a diluent for reconstitution.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Bayer Primo Testo Depot 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients: ["castor"],
        excipientPercentages: [44.5],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
        blurb: "Based on the classic Bayer depot formulation, combining testosterone enanthate with castor oil and traditional pharmaceutical solvents for long-acting release.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Bayer Rimobolan (primo) 100",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 36.261180679785326],
        excipients: ["castor"],
        excipientPercentages: [52.238819320214674],
        compounds: ["methenolone_enanthate"],
        compoundConcentration: [100],
        blurb: "Original Bayer Primobolan Depot formulation. A relatively low-concentration methenolone enanthate product known for its stability and gentle injection profile.",
        source: undefined,
    },
    {
        // Source: https://www.medicines.org.uk/emc/files/pil.14631.pdf
        id: crypto.randomUUID(),
        name: "Bayer Nebido 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 44.73],
        excipients: ["castor"],
        excipientPercentages: [29.020000000000007],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [250],
        blurb: "Original Nebido formulation. Uses testosterone undecanoate in a high-solvent castor oil vehicle designed for very long dosing intervals.",
        source: `https://www.medicines.org.uk/emc/files/pil.14631.pdf`,
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07
        id: crypto.randomUUID(),
        name: "DELESTROGEN Estradiol Valerate 10",
        solvents: ["chlorobutanol"],
        solventPercentages: [0.76],
        excipients: ["sesame"],
        excipientPercentages: [98.33090909090909],
        compounds: ["estradiol_valerate"],
        compoundConcentration: [10],
        blurb: "A pharmaceutical estradiol valerate preparation utilizing sesame oil and chlorobutanol. Representative of lower-strength estrogen injections.",
        source: `https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07`,
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07
        id: crypto.randomUUID(),
        name: "DELESTROGEN Estradiol Valerate 40",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 40],
        excipients: ["castor"],
        excipientPercentages: [54.36363636363636],
        compounds: ["estradiol_valerate"],
        compoundConcentration: [40],
        blurb: "Higher-concentration Delestrogen-style formulation using castor oil and benzyl benzoate to maintain solubility.",
        source: `https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=e8f94df9-0692-4462-a7f0-fe019a0a3f07`,
    },
    {
        // Source: https://www.drugs.com/vet/equipoise.html
        id: crypto.randomUUID(),
        name: "Equipoise 50",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [3],
        excipients: ["sesame"],
        excipientPercentages: [92.260663507109],
        compounds: ["boldenone_undecylenate"],
        compoundConcentration: [50],
        blurb: "Original veterinary boldenone undecylenate formulation based on the original Equipoise product information.",
        source: `https://www.drugs.com/vet/equipoise.html`,
    },
    {
        id: crypto.randomUUID(),
        name: "Cytex Test Cyp 100",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [2],
        excipients: ["ethyl_oleate"],
        excipientPercentages: [88.9],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [100],
        blurb: "A straightforward testosterone cypionate formula that relies on ethyl oleate as the primary carrier.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Cipla Test Cyp 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [0.91, 20],
        excipients: ["cottonseed"],
        excipientPercentages: [60.89],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [200],
        blurb: "A pharmaceutical testosterone cypionate product using cottonseed oil with modest solvent content.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "DECA-DURABOLIN 100",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [10],
        excipients: ["arachis"],
        excipientPercentages: [80.4],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [100],
        blurb: "The classic Deca-Durabolin formulation, featuring nandrolone decanoate in arachis oil.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "PARABOLAN 50",
        solvents: ["benzyl_alcohol", "ethanol"],
        solventPercentages: [4.79, 3.82],
        excipients: ["arachis"],
        excipientPercentages: [86.84],
        compounds: ["trenbolone_hexahydrobenzylcarbonate"],
        compoundConcentration: [50],
        blurb: "The original Parabolan recipe, containing trenbolone hexahydrobenzylcarbonate in a mixed-solvent system.",
        source: undefined,
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=a586b484-1b46-40b9-9508-fd28002ad383&type=display
        id: crypto.randomUUID(),
        name: "Watson Deca 200",
        solvents: ["benzyl_alcohol"],
        solventPercentages: [5],
        excipients: ["sesame"],
        excipientPercentages: [75.8],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [200],
        blurb: "Based on U.S. pharmaceutical nandrolone decanoate products manufactured by Watson. Contains only BA as solvent and solubilising agent.",
        source: `https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=a586b484-1b46-40b9-9508-fd28002ad383&type=display`,
    },
    {
        // Source: https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=82a98132-9d5f-40a5-8c4f-f52f2a5de60e
        id: crypto.randomUUID(),
        name: "Testosterone Enanthate (Eugia) 200",
        solvents: ["chlorobutanol"],
        solventPercentages: [0.5],
        excipients: ["sesame"],
        excipientPercentages: [80.7],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [200],
        blurb: "A modern pharmaceutical testosterone enanthate formulation utilizing chlorobutanol as the preservative and sesame oil as the carrier oil.",
        source: `https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=82a98132-9d5f-40a5-8c4f-f52f2a5de60e`,
    },
    {
        // Source: https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf
        id: crypto.randomUUID(),
        name: "SUSTANON 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 10],
        excipients: ["arachis"],
        excipientPercentages: [64.78252336448598],
        compounds: ["testosterone_propionate", "testosterone_phenylpropionate", "testosterone_isocaproate", "testosterone_decanoate"],
        compoundConcentration: [30, 60, 60, 100],
        blurb: "The famous multi-ester testosterone blend containing four distinct testosterone esters for a staggered release profile.",
        source: `https://www.medsafe.govt.nz/profs/datasheet/s/sustanoninj.pdf`,
    },
    {
        id: crypto.randomUUID(),
        name: "Testoboon CP 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [0.91, 22.362],
        excipients: ["arachis"],
        excipientPercentages: [53.977999999999994],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
        blurb: "A higher-strength testosterone cypionate product from India.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Photon's No G TNE 100",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2, 30],
        excipients: ["castor"],
        excipientPercentages: [59.1],
        compounds: ["testosterone_base"],
        compoundConcentration: [100],
        blurb: "A community-developed testosterone base formulation designed to avoid guaiacol while maintaining workable concentration.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Bananafeet's No G DHEA 50",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [6, 30],
        excipients: ["castor"],
        excipientPercentages: [59.23809523809524],
        compounds: ["dhea_base"],
        compoundConcentration: [50],
        blurb: "A DHEA injection concept emphasizing a guaiacol-free solvent system; based on Photon's original recipe.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "OEP's No G Anadrol 50",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.4375, 42.9299],
        excipients: ["castor"],
        excipientPercentages: [51.3325],
        compounds: ["anadrol"],
        compoundConcentration: [50],
        blurb: "Anadrol formulation developed around a no-guaiacol philosophy, relying on higher benzyl benzoate content instead.",
        source: undefined,
    },
    {
        id: crypto.randomUUID(),
        name: "Injectable Winstrol 50",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [10, 40],
        excipients: ["castor"],
        excipientPercentages: [45.449999999999996],
        compounds: ["winstrol"],
        compoundConcentration: [50],
        blurb: "A solution-based take on injectable stanozolol, distinct from the more common water-based suspension products.",
        source: undefined,
    },
    {
        // original is weak. made it a bit stronger (double)
        // source https://web.archive.org/web/20210126120007/https://steroid.to/sten-testosterone-cypionate-propionate
        id: crypto.randomUUID(),
        name: "STEN recipe",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [2.5, 20],
        excipients: ["arachis"],
        excipientPercentages: [66.4952380952381],
        compounds: ["dhea_base", "testosterone_propionate", "testosterone_cypionate"],
        compoundConcentration: [20, 25, 75],
        blurb: "Historical STEN recipe, combing DHEA and short and medium testosterone esters.",
        source: `https://web.archive.org/web/20210126120007/https://steroid.to/sten-testosterone-cypionate-propionate`,
    },

    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Mast E 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients: ["castor"],
        excipientPercentages: [49.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
        blurb: "Narta's original recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's NPP 150",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients: ["castor"],
        excipientPercentages: [55.3],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [150],
        blurb: "Narta's original recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477
        id: crypto.randomUUID(),
        name: "Narta's NPP 150 TPP 150",
        solvents: ["benzyl_alcohol", "benzyl_benzoate", "methyl_salicylate", "ethyl_lactate"],
        solventPercentages: [1.5, 15, 5, 15],
        excipients: ["castor"],
        excipientPercentages: [37.099999999999994],
        compounds: ["nandrolone_phenylpropionate", "testosterone_phenylpropionate"],
        compoundConcentration: [150, 150],
        blurb: "Narta's third generation higher-concentration recipes. Inspired by Bayer's patents and using non standard solvents and anesthetics.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test Iso 400",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients: ["castor"],
        excipientPercentages: [21.116822429906534],
        compounds: ["testosterone_isocaproate"],
        compoundConcentration: [400],
        blurb: "Narta's second higher-concentration recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477
        id: crypto.randomUUID(),
        name: "Narta's Test Iso 400",
        solvents: ["benzyl_alcohol", "benzyl_benzoate", "methyl_salicylate", "ethyl_lactate"],
        solventPercentages: [1.5, 15, 5, 15],
        excipients: ["castor"],
        excipientPercentages: [26.116822429906534],
        compounds: ["testosterone_isocaproate"],
        compoundConcentration: [400],
        blurb: "Narta's second higher-concentration recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477`,
    },

    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test D 350",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 30],
        excipients: ["castor"],
        excipientPercentages: [34.900000000000006],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [350],
        blurb: "Narta's original recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/
        id: crypto.randomUUID(),
        name: "Narta's Test D 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients: ["castor"],
        excipientPercentages: [10.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
        blurb: "Narta's second higher-concentration recipes. Inspired by Bayer's patents and higher benzyl benzoate formulations which they market.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/`,
    },
    {
        // Source: https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477
        id: crypto.randomUUID(),
        name: "Narta's Test D 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate", "methyl_salicylate", "ethyl_lactate"],
        solventPercentages: [1.5, 15, 5, 15],
        excipients: ["castor"],
        excipientPercentages: [15.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
        blurb: "Narta's third generation higher-concentration recipes. Inspired by Bayer's patents and using non standard solvents and anesthetics.",
        source: `https://thinksteroids.com/community/threads/castor-oil-experiments.134414781/post-3409477`,
    },

    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232
        id: crypto.randomUUID(),
        name: "Standard PIPless Test C",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.", 
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Deca",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [59.30],
        compounds: ["nandrolone_decanoate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren E",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [60.3],
        compounds: ["trenbolone_enanthate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Tren A",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [70],
        compounds: ["trenbolone_acetate"],
        compoundConcentration: [100],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless NPP",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [69.7],
        compounds: ["nandrolone_phenylpropionate"],
        compoundConcentration: [100],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test Prop",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 20],
        excipients: ["MCT"],
        excipientPercentages: [69.4],
        compounds: ["testosterone_propionate"],
        compoundConcentration: [100],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless EQ 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 18],
        excipients: ["MCT"],
        excipientPercentages: [33],
        compounds: ["boldenone_undecylenate"],
        compoundConcentration: [500],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Mast E 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 15],
        excipients: ["MCT"],
        excipientPercentages: [64.7],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Test E 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients: ["MCT"],
        excipientPercentages: [65],
        compounds: ["testosterone_enanthate"],
        compoundConcentration: [250],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "Standard PIPless Primo E 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 10],
        excipients: ["MCT"],
        excipientPercentages: [69.5],
        compounds: ["methenolone_enanthate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },

    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test C 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients: ["MCT"],
        excipientPercentages: [50.75],
        compounds: ["testosterone_cypionate"],
        compoundConcentration: [250],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Mast E 300",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 22],
        excipients: ["MCT"],
        excipientPercentages: [48.3],
        compounds: ["drostanolone_enanthate"],
        compoundConcentration: [300],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test D 500",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 24],
        excipients: ["MCT"],
        excipientPercentages: [26.5],
        compounds: ["testosterone_decanoate"],
        compoundConcentration: [500],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },

    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 200",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 25],
        excipients: ["MCT"],
        excipientPercentages: [54.099999999999994],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [200],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 250",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 40],
        excipients: ["castor"],
        excipientPercentages: [34.25],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [250],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        // Source:    https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232     id: crypto.randomUUID(),
        name: "High Concentration Test U 350",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [1.5, 50],
        excipients: ["castor"],
        excipientPercentages: [14.550000000000011],
        compounds: ["testosterone_undecanoate"],
        compoundConcentration: [350],
        blurb: "PIPless recipes designed or collected by Sampie and other community members.",
        source: `https://thinksteroids.com/community/threads/brew-recipes-bible.134426542/page-15#post-3678232`,
    },
    {
        id: crypto.randomUUID(),
        name: "Banana's No G Anadrolive 75",
        solvents: ["benzyl_alcohol", "benzyl_benzoate"],
        solventPercentages: [6, 40],
        excipients: ["olive"],
        excipientPercentages: [43.54999999999999],
        compounds: ["anadrol"],
        compoundConcentration: [75],
        blurb: `Experimental (failed) blend`, 
        source: undefined,
    },
    {
        // don't brew this
        // https://patents.google.com/patent/US2840508A/en
        id: crypto.randomUUID(),
        name: "US2840508A - Example 9",
        solvents: ["ethyl_lactate", "phenyl_salicylate"],
        solventPercentages: [19.41747572815534, 16],
        excipients: ["sesame"],
        excipientPercentages: [46.38252427184466],
        compounds: ["testosterone_propionate"],
        compoundConcentration: [200],
        blurb: `This from from the 1958 patent "Injectable steroid hormone preparations and method of making same"; presented for educational purposes (really). `,
        source: `https://patents.google.com/patent/US2840508A/en`,
    },
];
